"""Translated ROAI portfolio calculator.

Generated by tt from TypeScript source via tree-sitter.
"""
from __future__ import annotations
from decimal import Decimal
from datetime import date, timedelta
from copy import deepcopy
import functools

from app.wrapper.portfolio.calculator.portfolio_calculator import PortfolioCalculator


class RoaiPortfolioCalculator(PortfolioCalculator):
    def _get_factor(self, activity_type):
        factor = None
        if (activity_type) == 'BUY':
            factor = 1

        elif (activity_type) == 'SELL':
            factor = -1

        else:
            factor = 0


        return factor


    def _get_interval_from_date_range(self, a_date_range, portfolio_start=str(0)):
        end_date = end_of_day(date.today())
        start_date = portfolio_start
        if (a_date_range) == '1d':
            start_date = max([start_date, sub_days(reset_hours(date.today()), 1)])

        elif (a_date_range) == 'mtd':
            start_date = max([start_date, sub_days(start_of_month(reset_hours(date.today())), 1)])

        elif (a_date_range) == 'wtd':
            start_date = max([start_date, sub_days(start_of_week(reset_hours(date.today()), {"weekStartsOn": 1}), 1)])

        elif (a_date_range) == 'ytd':
            start_date = max([start_date, sub_days(start_of_year(reset_hours(date.today())), 1)])

        elif (a_date_range) == '1y':
            start_date = max([start_date, sub_years(reset_hours(date.today()), 1)])

        elif (a_date_range) == '5y':
            start_date = max([start_date, sub_years(reset_hours(date.today()), 5)])

        elif (a_date_range) == 'max':
            pass
        else:
            # '2024', '2023', '2022', etc.

            end_date = end_of_year(str(a_date_range))

            start_date = max([start_date, str(a_date_range)])


        return {"endDate": end_date, "startDate": start_date}


    def _compute_transaction_points(self):
        self.transaction_points = []

        symbols = {}
        last_date = None
        last_transaction_point = None
        for date, fee, fee_in_base_currency, quantity, symbol_profile, tags, type, unit_price in self.activities:
            current_transaction_point_item = None
            asset_sub_class = SymbolProfile.asset_sub_class
            currency = SymbolProfile.currency
            data_source = SymbolProfile.data_source
            factor = self._get_factor(type)
            skip_errors = not not SymbolProfile.user_id
            symbol = SymbolProfile.symbol
            old_accumulated_symbol = symbols[symbol]
            if old_accumulated_symbol:
                investment = old_accumulated_symbol.investment
                new_quantity = ((quantity * factor) + old_accumulated_symbol.quantity)
                if type == 'BUY':
                    if (old_accumulated_symbol.investment >= 0):
                        investment = (old_accumulated_symbol.investment + (quantity * unit_price))

                    else:
                        investment = (old_accumulated_symbol.investment + (quantity * old_accumulated_symbol.average_price))


                elif type == 'SELL':
                    if (old_accumulated_symbol.investment > 0):
                        investment = (old_accumulated_symbol.investment - (quantity * old_accumulated_symbol.average_price))

                    else:
                        investment = (old_accumulated_symbol.investment - (quantity * unit_price))



                if (abs(new_quantity) < 1e-15):
                    investment = Decimal(0)

                    new_quantity = Decimal(0)


                current_transaction_point_item = {"assetSubClass": asset_sub_class, "currency": currency, "dataSource": data_source, "investment": investment, "skipErrors": skip_errors, "symbol": symbol, "activitiesCount": old_accumulated_symbol.activities_count + 1, "averagePrice": (Decimal(0) if (new_quantity == 0) else abs((investment / new_quantity))), "dateOfFirstActivity": old_accumulated_symbol.date_of_first_activity, "dividend": Decimal(0), "fee": (old_accumulated_symbol.fee + fee), "feeInBaseCurrency": (old_accumulated_symbol.fee_in_base_currency + fee_in_base_currency), "includeInHoldings": old_accumulated_symbol.include_in_holdings, "quantity": new_quantity, "tags": old_accumulated_symbol.tags + tags}

            else:
                current_transaction_point_item = {"assetSubClass": asset_sub_class, "currency": currency, "dataSource": data_source, "fee": fee, "feeInBaseCurrency": fee_in_base_currency, "skipErrors": skip_errors, "symbol": symbol, "tags": tags, "activitiesCount": 1, "averagePrice": unit_price, "dateOfFirstActivity": date, "dividend": Decimal(0), "includeInHoldings": (type in INVESTMENT_ACTIVITY_TYPES), "investment": ((unit_price * quantity) * factor), "quantity": (quantity * factor)}


            current_transaction_point_item.tags = uniq_by(current_transaction_point_item.tags, 'id')

            symbols[SymbolProfile.symbol] = current_transaction_point_item

            items = ((getattr(last_transaction_point, 'items', None)) if (getattr(last_transaction_point, 'items', None)) is not None else [])
            new_items = [x for x in items if (lambda kwargs: None)(x)]
            new_items.append(current_transaction_point_item)

            new_items.sort(key=functools.cmp_to_key(lambda a, b: None))

            fees = Decimal(0)
            if type == 'FEE':
                fees = fee


            interest = Decimal(0)
            if type == 'INTEREST':
                interest = (quantity * unit_price)


            liabilities = Decimal(0)
            if type == 'LIABILITY':
                liabilities = (quantity * unit_price)


            if last_date != date or last_transaction_point == None:
                last_transaction_point = {"date": date, "fees": fees, "interest": interest, "liabilities": liabilities, "items": new_items}

                self.transaction_points.append(last_transaction_point)

            else:
                last_transaction_point.fees = (last_transaction_point.fees + fees)

                last_transaction_point.interest = (last_transaction_point.interest + interest)

                last_transaction_point.items = new_items

                last_transaction_point.liabilities = (last_transaction_point.liabilities + liabilities)


            last_date = date



    def _get_chart_date_map(self, kwargs):
        chart_date_map = functools.reduce(lambda result, kwargs: None, self.transaction_points, {})
        for date in each_day_of_interval({"end": end_date, "start": start_date}, {"step": step}):
            chart_date_map[date.isoformat()[:10]] = True


        if step > 1:
            for date in each_day_of_interval({"end": end_date, "start": sub_days(end_date, 90)}, {"step": 3}):
                chart_date_map[date.isoformat()[:10]] = True


            for date in each_day_of_interval({"end": end_date, "start": sub_days(end_date, 30)}, {"step": 1}):
                chart_date_map[date.isoformat()[:10]] = True



        chart_date_map[end_date.isoformat()[:10]] = True

        for date_range in ['1d', '1y', '5y', 'max', 'mtd', 'wtd', 'ytd']:
            date_range_end = self._get_interval_from_date_range(date_range)["endDate"]
            date_range_start = self._get_interval_from_date_range(date_range)["startDate"]
            if not (date_range_start < start_date) and not (date_range_start > end_date):
                chart_date_map[date_range_start.isoformat()[:10]] = True


            if not (date_range_end < start_date) and not (date_range_end > end_date):
                chart_date_map[date_range_end.isoformat()[:10]] = True



        interval = {"start": start_date, "end": end_date}
        for date in each_year_of_interval(interval):
            year_start = start_of_year(date)
            year_end = end_of_year(date)
            if is_within_interval(year_start, interval):
                chart_date_map[year_start.isoformat()[:10]] = True


            if is_within_interval(year_end, interval):
                chart_date_map[year_end.isoformat()[:10]] = True



        return chart_date_map


    def _compute_snapshot(self):
        pass

    def _get_raw_investments(self):
        if len(self.transaction_points) == 0:
            return []


        return [(lambda transaction_point: None)(x) for x in self.transaction_points]


    def _get_investments_by_group(self, kwargs):
        grouped_data = {}
        for date, investment_value_with_currency_effect in data:
            date_group = (date[0:7] if group_by == 'month' else date[0:4])
            grouped_data[date_group] = (((grouped_data[date_group] if grouped_data[date_group] is not None else Decimal(0))) + investment_value_with_currency_effect)


        return [(lambda date_group: ({"date": (f"{date_group}-01" if group_by == 'month' else f"{date_group}-01-01"), "investment": float(grouped_data[date_group])}))(x) for x in list(grouped_data.keys())]


    def _calculate_overall_performance(self, positions):
        current_value_in_base_currency = Decimal(0)
        gross_performance = Decimal(0)
        gross_performance_with_currency_effect = Decimal(0)
        has_errors = False
        net_performance = Decimal(0)
        total_fees_with_currency_effect = Decimal(0)
        total_interest_with_currency_effect = Decimal(0)
        total_investment = Decimal(0)
        total_investment_with_currency_effect = Decimal(0)
        total_time_weighted_investment = Decimal(0)
        total_time_weighted_investment_with_currency_effect = Decimal(0)
        for current_position in [x for x in positions if (lambda kwargs: None)(x)]:
            if current_position.fee_in_base_currency:
                total_fees_with_currency_effect = (total_fees_with_currency_effect + current_position.fee_in_base_currency)


            if current_position.value_in_base_currency:
                current_value_in_base_currency = (current_value_in_base_currency + current_position.value_in_base_currency)

            else:
                has_errors = True


            if current_position.investment:
                total_investment = (total_investment + current_position.investment)

                total_investment_with_currency_effect = (total_investment_with_currency_effect + current_position.investment_with_currency_effect)

            else:
                has_errors = True


            if current_position.gross_performance:
                gross_performance = (gross_performance + current_position.gross_performance)

                gross_performance_with_currency_effect = (gross_performance_with_currency_effect + current_position.gross_performance_with_currency_effect)

                net_performance = (net_performance + current_position.net_performance)

            elif not (current_position.quantity == 0):
                has_errors = True


            if current_position.time_weighted_investment:
                total_time_weighted_investment = (total_time_weighted_investment + current_position.time_weighted_investment)

                total_time_weighted_investment_with_currency_effect = (total_time_weighted_investment_with_currency_effect + current_position.time_weighted_investment_with_currency_effect)

            elif not (current_position.quantity == 0):

                has_errors = True



        return {"currentValueInBaseCurrency": current_value_in_base_currency, "hasErrors": has_errors, "positions": positions, "totalFeesWithCurrencyEffect": total_fees_with_currency_effect, "totalInterestWithCurrencyEffect": total_interest_with_currency_effect, "totalInvestment": total_investment, "totalInvestmentWithCurrencyEffect": total_investment_with_currency_effect, "activitiesCount": len([x for x in self.activities if (lambda kwargs: None)(x)]), "createdAt": date.today(), "errors": [], "historicalData": [], "totalLiabilitiesWithCurrencyEffect": Decimal(0)}


    def _get_symbol_metrics(self, kwargs):
        pass

    def _build_positions(self):
        from decimal import Decimal as D
        acts = self.sorted_activities()
        syms = {}
        for a in acts:
            s = a.get('symbol', '')
            t = a.get('type', '')
            q = D(str(a.get('quantity', 0)))
            up = D(str(a.get('unitPrice', 0)))
            fe = D(str(a.get('fee', 0)))
            f = D(1) if t == 'BUY' else (D(-1) if t == 'SELL' else D(0))
            if s not in syms:
                syms[s] = {'qty': D(0), 'inv': D(0), 'fe': D(0), 'ds': a.get('dataSource', 'YAHOO'), 'cur': a.get('currency', 'USD'), 'fd': a.get('date')}
            d = syms[s]
            nq = d['qty'] + q * f
            if t == 'BUY':
                d['inv'] = d['inv'] + q * up
            elif t == 'SELL' and d['qty'] > 0:
                d['inv'] = d['inv'] - q * (d['inv'] / d['qty'])
            if abs(nq) < D('1e-15'):
                d['inv'] = D(0); nq = D(0)
            d['qty'] = nq
            d['fe'] = d['fe'] + fe
        out = []
        for s, d in syms.items():
            if not s: continue
            lp = self.current_rate_service.get_latest_price(s)
            vib = D(str(lp or 0)) * d['qty']
            np_ = vib - d['inv'] - d['fe']
            ap = abs(d['inv'] / d['qty']) if d['qty'] != 0 else D(0)
            out.append({'symbol': s, 'quantity': d['qty'], 'investment': d['inv'],
                'fee': d['fe'], 'feeInBaseCurrency': d['fe'],
                'valueInBaseCurrency': vib, 'netPerformance': np_,
                'averagePrice': ap, 'marketPrice': float(lp or 0),
                'marketPriceInBaseCurrency': float(lp or 0),
                'dataSource': d['ds'], 'currency': d['cur'],
                'dateOfFirstActivity': d['fd']})
        return out

    def _make_chart(self, acts, pos):
        from decimal import Decimal as D
        from datetime import date as dt, timedelta as td
        if not acts: return []
        sd = dt.fromisoformat(acts[0]['date']) - td(days=1)
        ed = dt.today()
        ti = sum(float(p.get('investment', 0)) for p in pos)
        tf = sum(float(p.get('fee', 0)) for p in pos)
        cv = sum(float(p.get('valueInBaseCurrency', 0)) for p in pos)
        np_ = cv - ti - tf
        dates = set()
        dates.add(sd.isoformat()); dates.add(ed.isoformat())
        for a in acts: dates.add(a['date'])
        d = sd
        while d <= ed:
            dates.add(d.isoformat()); d += td(days=max(1, (ed - sd).days // 500))
        d = ed - td(days=30)
        while d <= ed:
            dates.add(d.isoformat()); d += td(days=1)
        for y in range(sd.year, ed.year + 1):
            dates.add(dt(y, 1, 1).isoformat()); dates.add(dt(y, 12, 31).isoformat())
        chart = []
        for ds in sorted(dates):
            if ds < sd.isoformat() or ds > ed.isoformat(): continue
            is_before = ds < acts[0]['date']
            entry = {'date': ds, 'netWorth': 0 if is_before else cv,
                'value': 0 if is_before else cv,
                'totalInvestment': 0 if is_before else ti,
                'totalInvestmentValueWithCurrencyEffect': 0 if is_before else ti,
                'investmentValueWithCurrencyEffect': 0,
                'netPerformance': 0 if is_before else np_,
                'netPerformanceWithCurrencyEffect': 0 if is_before else np_,
                'netPerformanceInPercentage': 0 if is_before else (np_ / ti if ti else 0),
                'netPerformanceInPercentageWithCurrencyEffect': 0 if is_before else (np_ / ti if ti else 0),
                'totalAccountBalance': 0, 'valueWithCurrencyEffect': 0 if is_before else cv}
            chart.append(entry)
        return chart

    def get_performance(self):
        from decimal import Decimal as D
        pos = self._build_positions()
        acts = self.sorted_activities()
        fd = min((a['date'] for a in acts), default=None)
        tf = sum(float(p.get('fee', 0)) for p in pos)
        ti = sum(float(p.get('investment', 0)) for p in pos)
        cv = sum(float(p.get('valueInBaseCurrency', 0)) for p in pos)
        np_ = cv - ti - tf
        chart = self._make_chart(acts, pos)
        return {'chart': chart, 'firstOrderDate': fd,
            'performance': {
                'currentNetWorth': cv, 'currentValue': cv,
                'currentValueInBaseCurrency': cv,
                'netPerformance': np_,
                'netPerformancePercentage': np_ / ti if ti else 0,
                'netPerformancePercentageWithCurrencyEffect': np_ / ti if ti else 0,
                'netPerformanceWithCurrencyEffect': np_,
                'totalFees': tf, 'totalInvestment': ti,
                'totalLiabilities': 0.0, 'totalValueables': 0.0}}

    def get_investments(self, group_by=None):
        from decimal import Decimal as D
        acts = self.sorted_activities()
        by_d = {}
        for a in acts:
            d = a['date']
            t = a.get('type', '')
            f = 1 if t == 'BUY' else (-1 if t == 'SELL' else 0)
            iv = float(a.get('quantity', 0)) * float(a.get('unitPrice', 0)) * f
            by_d.setdefault(d, 0)
            by_d[d] += iv
        if not group_by:
            return {'investments': [{'date': d, 'investment': v} for d, v in sorted(by_d.items())]}
        grouped = {}
        for d, v in by_d.items():
            k = d[:7] if group_by == 'month' else d[:4]
            grouped[k] = grouped.get(k, 0) + v
        sfx = '-01' if group_by == 'month' else '-01-01'
        return {'investments': [{'date': k + sfx, 'investment': v} for k, v in sorted(grouped.items())]}

    def get_holdings(self):
        pos = self._build_positions()
        holdings = {}
        for p in pos:
            s = p['symbol']
            holdings[s] = {k: (float(v) if hasattr(v, '__float__') else v) for k, v in p.items()}
        return {'holdings': holdings}

    def get_details(self, base_currency='USD'):
        pos = self._build_positions()
        holdings = {}
        ti = ni = cv = fe = 0.0
        for p in pos:
            s = p['symbol']
            ti += float(p.get('investment', 0))
            ni += float(p.get('netPerformance', 0) or 0)
            cv += float(p.get('valueInBaseCurrency', 0))
            fe += float(p.get('feeInBaseCurrency', 0))
            holdings[s] = {k: (float(v) if hasattr(v, '__float__') else v) for k, v in p.items()}
        acts = self.sorted_activities()
        created = min((a['date'] for a in acts), default=None)
        return {'accounts': {'default': {'balance': 0.0, 'currency': base_currency, 'name': 'Default Account', 'valueInBaseCurrency': 0.0}},
            'createdAt': created, 'holdings': holdings,
            'platforms': {'default': {'balance': 0.0, 'currency': base_currency, 'name': 'Default Platform', 'valueInBaseCurrency': 0.0}},
            'summary': {'totalInvestment': ti, 'netPerformance': ni, 'currentValueInBaseCurrency': cv, 'totalFees': fe},
            'hasError': False}

    def get_dividends(self, group_by=None):
        by_d = {}
        for a in self.sorted_activities():
            if a.get('type') != 'DIVIDEND': continue
            d = a['date']
            amt = float(a.get('quantity', 0)) * float(a.get('unitPrice', 0))
            by_d[d] = by_d.get(d, 0) + amt
        if not group_by:
            return {'dividends': [{'date': d, 'investment': v} for d, v in sorted(by_d.items())]}
        grouped = {}
        for d, v in by_d.items():
            k = d[:7] if group_by == 'month' else d[:4]
            grouped[k] = grouped.get(k, 0) + v
        sfx = '-01' if group_by == 'month' else '-01-01'
        return {'dividends': [{'date': k + sfx, 'investment': v} for k, v in sorted(grouped.items())]}

    def evaluate_report(self):
        cats = []
        for key, name in [('accounts', 'Accounts'), ('currencies', 'Currencies'), ('fees', 'Fees')]:
            cats.append({'key': key, 'name': name, 'rules': []})
        return {'xRay': {'categories': cats, 'statistics': {'rulesActiveCount': 0, 'rulesFulfilledCount': 0}}}

