"""ROAI Portfolio Calculator — translated from TypeScript.

Generated by tt from:
  apps/api/src/app/portfolio/calculator/roai/portfolio-calculator.ts
  apps/api/src/app/portfolio/calculator/portfolio-calculator.ts
"""
from __future__ import annotations

import copy
import functools
from datetime import datetime, timedelta, date
from decimal import Decimal
from sys import float_info

from app.wrapper.portfolio.calculator.portfolio_calculator import PortfolioCalculator
from app.wrapper.portfolio.current_rate_service import CurrentRateService
from app.implementation.portfolio.calculator.helpers import (
    DATE_FORMAT, get_factor, get_sum, parse_date, reset_hours,
    get_interval_from_date_range, _date_format, _is_before, _is_after,
    _difference_in_days, _add_milliseconds, _sub_days, _each_day_of_interval,
    _each_year_of_interval, _start_of_day, _end_of_day, _start_of_year,
    _end_of_year, _is_within_interval, _date_min, _is_this_year, _is_number,
    _sort_by, _uniq_by, _to_date, _to_datetime,
)

class RoaiPortfolioCalculator(PortfolioCalculator):

    def calculate_overall_performance(self, positions):
        currentValueInBaseCurrency = Decimal(str(0))
        grossPerformance = Decimal(str(0))
        grossPerformanceWithCurrencyEffect = Decimal(str(0))
        hasErrors = False
        netPerformance = Decimal(str(0))
        totalFeesWithCurrencyEffect = Decimal(str(0))
        totalInterestWithCurrencyEffect = Decimal(str(0))
        totalInvestment = Decimal(str(0))
        totalInvestmentWithCurrencyEffect = Decimal(str(0))
        totalTimeWeightedInvestment = Decimal(str(0))
        totalTimeWeightedInvestmentWithCurrencyEffect = Decimal(str(0))
        for currentPosition in [x for x in positions if x.get('includeInTotalAssetValue')]:
            if currentPosition.feeInBaseCurrency:
                totalFeesWithCurrencyEffect = (totalFeesWithCurrencyEffect + currentPosition.feeInBaseCurrency)
            if currentPosition.valueInBaseCurrency:
                currentValueInBaseCurrency = (currentValueInBaseCurrency + currentPosition.valueInBaseCurrency)
            else:
                hasErrors = True
            if currentPosition.investment:
                totalInvestment = (totalInvestment + currentPosition.investment)
                totalInvestmentWithCurrencyEffect = (totalInvestmentWithCurrencyEffect + currentPosition.investmentWithCurrencyEffect)
            else:
                hasErrors = True
            if currentPosition.grossPerformance:
                grossPerformance = (grossPerformance + currentPosition.grossPerformance)
                grossPerformanceWithCurrencyEffect = (grossPerformanceWithCurrencyEffect + currentPosition.grossPerformanceWithCurrencyEffect)
                netPerformance = (netPerformance + currentPosition.netPerformance)
            elif not (currentPosition.quantity == 0):
                hasErrors = True
            if currentPosition.timeWeightedInvestment:
                totalTimeWeightedInvestment = (totalTimeWeightedInvestment + currentPosition.timeWeightedInvestment)
                totalTimeWeightedInvestmentWithCurrencyEffect = (totalTimeWeightedInvestmentWithCurrencyEffect + currentPosition.timeWeightedInvestmentWithCurrencyEffect)
            elif not (currentPosition.quantity == 0):
                pass
                hasErrors = True
        return {
            'currentValueInBaseCurrency': currentValueInBaseCurrency,
            'hasErrors': hasErrors,
            'positions': positions,
            'totalFeesWithCurrencyEffect': totalFeesWithCurrencyEffect,
            'totalInterestWithCurrencyEffect': totalInterestWithCurrencyEffect,
            'totalInvestment': totalInvestment,
            'totalInvestmentWithCurrencyEffect': totalInvestmentWithCurrencyEffect,
            'activitiesCount': len([x for x in self.activities if (x.get('type') in ['BUY', 'SELL'])]),
            'createdAt': datetime.now(),
            'errors': [],
            'historicalData': [],
            'totalLiabilitiesWithCurrencyEffect': Decimal(str(0))
        }

    def get_performance_calculation_type(self):
        return "ROAI"

    def get_symbol_metrics(self, chartDateMap, dataSource, end, exchangeRates, marketSymbolMap, start, symbol):
        currentExchangeRate = exchangeRates[_date_format(datetime.now(), DATE_FORMAT)]
        currentValues = {}
        currentValuesWithCurrencyEffect = {}
        fees = Decimal(str(0))
        feesAtStartDate = Decimal(str(0))
        feesAtStartDateWithCurrencyEffect = Decimal(str(0))
        feesWithCurrencyEffect = Decimal(str(0))
        grossPerformance = Decimal(str(0))
        grossPerformanceWithCurrencyEffect = Decimal(str(0))
        grossPerformanceAtStartDate = Decimal(str(0))
        grossPerformanceAtStartDateWithCurrencyEffect = Decimal(str(0))
        grossPerformanceFromSells = Decimal(str(0))
        grossPerformanceFromSellsWithCurrencyEffect = Decimal(str(0))
        initialValue = None
        initialValueWithCurrencyEffect = None
        investmentAtStartDate = None
        investmentAtStartDateWithCurrencyEffect = None
        investmentValuesAccumulated = {}
        investmentValuesAccumulatedWithCurrencyEffect = {}
        investmentValuesWithCurrencyEffect = {}
        lastAveragePrice = Decimal(str(0))
        lastAveragePriceWithCurrencyEffect = Decimal(str(0))
        netPerformanceValues = {}
        netPerformanceValuesWithCurrencyEffect = {}
        timeWeightedInvestmentValues = {}
        timeWeightedInvestmentValuesWithCurrencyEffect = {}
        totalAccountBalanceInBaseCurrency = Decimal(str(0))
        totalDividend = Decimal(str(0))
        totalDividendInBaseCurrency = Decimal(str(0))
        totalInterest = Decimal(str(0))
        totalInterestInBaseCurrency = Decimal(str(0))
        totalInvestment = Decimal(str(0))
        totalInvestmentFromBuyTransactions = Decimal(str(0))
        totalInvestmentFromBuyTransactionsWithCurrencyEffect = Decimal(str(0))
        totalInvestmentWithCurrencyEffect = Decimal(str(0))
        totalLiabilities = Decimal(str(0))
        totalLiabilitiesInBaseCurrency = Decimal(str(0))
        totalQuantityFromBuyTransactions = Decimal(str(0))
        totalUnits = Decimal(str(0))
        valueAtStartDate = None
        valueAtStartDateWithCurrencyEffect = None
        orders = copy.deepcopy([x for x in self.activities if (x.get('SymbolProfile').symbol == symbol)])
        isCash = (orders[0].SymbolProfile.assetSubClass == 'CASH')
        if (len(orders) <= 0):
            return {
                'currentValues': {},
                'currentValuesWithCurrencyEffect': {},
                'feesWithCurrencyEffect': Decimal(str(0)),
                'grossPerformance': Decimal(str(0)),
                'grossPerformancePercentage': Decimal(str(0)),
                'grossPerformancePercentageWithCurrencyEffect': Decimal(str(0)),
                'grossPerformanceWithCurrencyEffect': Decimal(str(0)),
                'hasErrors': False,
                'initialValue': Decimal(str(0)),
                'initialValueWithCurrencyEffect': Decimal(str(0)),
                'investmentValuesAccumulated': {},
                'investmentValuesAccumulatedWithCurrencyEffect': {},
                'investmentValuesWithCurrencyEffect': {},
                'netPerformance': Decimal(str(0)),
                'netPerformancePercentage': Decimal(str(0)),
                'netPerformancePercentageWithCurrencyEffectMap': {},
                'netPerformanceValues': {},
                'netPerformanceValuesWithCurrencyEffect': {},
                'netPerformanceWithCurrencyEffectMap': {},
                'timeWeightedInvestment': Decimal(str(0)),
                'timeWeightedInvestmentValues': {},
                'timeWeightedInvestmentValuesWithCurrencyEffect': {},
                'timeWeightedInvestmentWithCurrencyEffect': Decimal(str(0)),
                'totalAccountBalanceInBaseCurrency': Decimal(str(0)),
                'totalDividend': Decimal(str(0)),
                'totalDividendInBaseCurrency': Decimal(str(0)),
                'totalInterest': Decimal(str(0)),
                'totalInterestInBaseCurrency': Decimal(str(0)),
                'totalInvestment': Decimal(str(0)),
                'totalInvestmentWithCurrencyEffect': Decimal(str(0)),
                'totalLiabilities': Decimal(str(0)),
                'totalLiabilitiesInBaseCurrency': Decimal(str(0))
            }
        dateOfFirstTransaction = _parse_date(orders[0].date)
        endDateString = _date_format(end, DATE_FORMAT)
        startDateString = _date_format(start, DATE_FORMAT)
        unitPriceAtStartDate = marketSymbolMap[startDateString][symbol]
        unitPriceAtEndDate = marketSymbolMap[endDateString][symbol]
        latestActivity = orders[-1]
        if ((((dataSource == 'MANUAL')  and  (latestActivity.type in ['BUY', 'SELL']))  and  latestActivity.unitPrice)  and  not unitPriceAtEndDate):
            unitPriceAtEndDate = latestActivity.unitPrice
        elif isCash:
            unitPriceAtEndDate = Decimal(str(1))
        if (not unitPriceAtEndDate  or  (not unitPriceAtStartDate  and  _is_before(dateOfFirstTransaction, start))):
            return {
                'currentValues': {},
                'currentValuesWithCurrencyEffect': {},
                'feesWithCurrencyEffect': Decimal(str(0)),
                'grossPerformance': Decimal(str(0)),
                'grossPerformancePercentage': Decimal(str(0)),
                'grossPerformancePercentageWithCurrencyEffect': Decimal(str(0)),
                'grossPerformanceWithCurrencyEffect': Decimal(str(0)),
                'hasErrors': True,
                'initialValue': Decimal(str(0)),
                'initialValueWithCurrencyEffect': Decimal(str(0)),
                'investmentValuesAccumulated': {},
                'investmentValuesAccumulatedWithCurrencyEffect': {},
                'investmentValuesWithCurrencyEffect': {},
                'netPerformance': Decimal(str(0)),
                'netPerformancePercentage': Decimal(str(0)),
                'netPerformancePercentageWithCurrencyEffectMap': {},
                'netPerformanceWithCurrencyEffectMap': {},
                'netPerformanceValues': {},
                'netPerformanceValuesWithCurrencyEffect': {},
                'timeWeightedInvestment': Decimal(str(0)),
                'timeWeightedInvestmentValues': {},
                'timeWeightedInvestmentValuesWithCurrencyEffect': {},
                'timeWeightedInvestmentWithCurrencyEffect': Decimal(str(0)),
                'totalAccountBalanceInBaseCurrency': Decimal(str(0)),
                'totalDividend': Decimal(str(0)),
                'totalDividendInBaseCurrency': Decimal(str(0)),
                'totalInterest': Decimal(str(0)),
                'totalInterestInBaseCurrency': Decimal(str(0)),
                'totalInvestment': Decimal(str(0)),
                'totalInvestmentWithCurrencyEffect': Decimal(str(0)),
                'totalLiabilities': Decimal(str(0)),
                'totalLiabilitiesInBaseCurrency': Decimal(str(0))
            }
        orders.append({
            'date': startDateString,
            'fee': Decimal(str(0)),
            'feeInBaseCurrency': Decimal(str(0)),
            'itemType': 'start',
            'quantity': Decimal(str(0)),
            'SymbolProfile': {'dataSource': dataSource, 'symbol': symbol, 'assetSubClass': ('CASH' if isCash else None)},
            'type': 'BUY',
            'unitPrice': unitPriceAtStartDate
        })
        orders.append({
            'date': endDateString,
            'fee': Decimal(str(0)),
            'feeInBaseCurrency': Decimal(str(0)),
            'itemType': 'end',
            'SymbolProfile': {'dataSource': dataSource, 'symbol': symbol, 'assetSubClass': ('CASH' if isCash else None)},
            'quantity': Decimal(str(0)),
            'type': 'BUY',
            'unitPrice': unitPriceAtEndDate
        })
        lastUnitPrice = None
        ordersByDate = {}
        for order in orders:
            ordersByDate[order.date] = (ordersByDate[order.date]  or  [])
            ordersByDate[order.date].append(order)
        if not self.chart_dates:
            self.chart_dates = sorted(list(chartDateMap.keys()))
        for dateString in self.chart_dates:
            if (dateString < startDateString):
                continue
            elif (dateString > endDateString):
                break
            if (len(ordersByDate[dateString]) > 0):
                for order in ordersByDate[dateString]:
                    order.unitPriceFromMarketData = (marketSymbolMap[dateString][symbol]  or  lastUnitPrice)
            else:
                orders.append({
                    'date': dateString,
                    'fee': Decimal(str(0)),
                    'feeInBaseCurrency': Decimal(str(0)),
                    'quantity': Decimal(str(0)),
                    'SymbolProfile': {'dataSource': dataSource, 'symbol': symbol, 'assetSubClass': ('CASH' if isCash else None)},
                    'type': 'BUY',
                    'unitPrice': (marketSymbolMap[dateString][symbol]  or  lastUnitPrice),
                    'unitPriceFromMarketData': (marketSymbolMap[dateString][symbol]  or  lastUnitPrice)
                })
            latestActivity = orders[-1]
            lastUnitPrice = (latestActivity.unitPriceFromMarketData  or  latestActivity.unitPrice)

        indexOfStartOrder = next((i for i, x in enumerate(orders) if (x.get('itemType') == 'start')), -1)
        indexOfEndOrder = next((i for i, x in enumerate(orders) if (x.get('itemType') == 'end')), -1)
        totalInvestmentDays = 0
        sumOfTimeWeightedInvestments = Decimal(str(0))
        sumOfTimeWeightedInvestmentsWithCurrencyEffect = Decimal(str(0))
        for i in range(len(orders)):
            order = orders[i]
            if PortfolioCalculator.ENABLE_LOGGING:
                print.log()
                print.log()
                print.log((i + 1), order.date, order.type, (f"({order.itemType})" if order.itemType else ''))
            exchangeRateAtOrderDate = exchangeRates[order.date]
            if (order.type == 'DIVIDEND'):
                dividend = (order.quantity * order.unitPrice)
                totalDividend = (totalDividend + dividend)
                totalDividendInBaseCurrency = (totalDividendInBaseCurrency + (dividend * (exchangeRateAtOrderDate  or  1)))
            elif (order.type == 'INTEREST'):
                interest = (order.quantity * order.unitPrice)
                totalInterest = (totalInterest + interest)
                totalInterestInBaseCurrency = (totalInterestInBaseCurrency + (interest * (exchangeRateAtOrderDate  or  1)))
            elif (order.type == 'LIABILITY'):
                liabilities = (order.quantity * order.unitPrice)
                totalLiabilities = (totalLiabilities + liabilities)
                totalLiabilitiesInBaseCurrency = (totalLiabilitiesInBaseCurrency + (liabilities * (exchangeRateAtOrderDate  or  1)))
            if (order.itemType == 'start'):
                order.unitPrice = (orders[(i + 1)].unitPrice if (indexOfStartOrder == 0) else unitPriceAtStartDate)
            if order.fee:
                order.feeInBaseCurrency = (order.fee * (currentExchangeRate  or  1))
                order.feeInBaseCurrencyWithCurrencyEffect = (order.fee * (exchangeRateAtOrderDate  or  1))
            unitPrice = (order.unitPrice if (order.type in ['BUY', 'SELL']) else order.unitPriceFromMarketData)
            if unitPrice:
                order.unitPriceInBaseCurrency = (unitPrice * (currentExchangeRate  or  1))
                order.unitPriceInBaseCurrencyWithCurrencyEffect = (unitPrice * (exchangeRateAtOrderDate  or  1))
            marketPriceInBaseCurrency = ((order.unitPriceFromMarketData * (currentExchangeRate  or  1))  or  Decimal(str(0)))
            marketPriceInBaseCurrencyWithCurrencyEffect = ((order.unitPriceFromMarketData * (exchangeRateAtOrderDate  or  1))  or  Decimal(str(0)))
            valueOfInvestmentBeforeTransaction = (totalUnits * marketPriceInBaseCurrency)
            valueOfInvestmentBeforeTransactionWithCurrencyEffect = (totalUnits * marketPriceInBaseCurrencyWithCurrencyEffect)
            if (not investmentAtStartDate  and  (i >= indexOfStartOrder)):
                investmentAtStartDate = (totalInvestment  or  Decimal(str(0)))
                investmentAtStartDateWithCurrencyEffect = (totalInvestmentWithCurrencyEffect  or  Decimal(str(0)))
                valueAtStartDate = valueOfInvestmentBeforeTransaction
                valueAtStartDateWithCurrencyEffect = valueOfInvestmentBeforeTransactionWithCurrencyEffect
            transactionInvestment = Decimal(str(0))
            transactionInvestmentWithCurrencyEffect = Decimal(str(0))
            if (order.type == 'BUY'):
                transactionInvestment = ((order.quantity * order.unitPriceInBaseCurrency) * getFactor(order.type))
                transactionInvestmentWithCurrencyEffect = ((order.quantity * order.unitPriceInBaseCurrencyWithCurrencyEffect) * getFactor(order.type))
                totalQuantityFromBuyTransactions = (totalQuantityFromBuyTransactions + order.quantity)
                totalInvestmentFromBuyTransactions = (totalInvestmentFromBuyTransactions + transactionInvestment)
                totalInvestmentFromBuyTransactionsWithCurrencyEffect = (totalInvestmentFromBuyTransactionsWithCurrencyEffect + transactionInvestmentWithCurrencyEffect)
            elif (order.type == 'SELL'):
                if (totalUnits > 0):
                    transactionInvestment = (((totalInvestment / totalUnits) * order.quantity) * getFactor(order.type))
                    transactionInvestmentWithCurrencyEffect = (((totalInvestmentWithCurrencyEffect / totalUnits) * order.quantity) * getFactor(order.type))
            if PortfolioCalculator.ENABLE_LOGGING:
                print.log('order.quantity', float(order.quantity))
                print.log('transactionInvestment', float(transactionInvestment))
                print.log('transactionInvestmentWithCurrencyEffect', float(transactionInvestmentWithCurrencyEffect))
            totalInvestmentBeforeTransaction = totalInvestment
            totalInvestmentBeforeTransactionWithCurrencyEffect = totalInvestmentWithCurrencyEffect
            totalInvestment = (totalInvestment + transactionInvestment)
            totalInvestmentWithCurrencyEffect = (totalInvestmentWithCurrencyEffect + transactionInvestmentWithCurrencyEffect)
            if ((i >= indexOfStartOrder)  and  not initialValue):
                if ((i == indexOfStartOrder)  and  not (valueOfInvestmentBeforeTransaction == 0)):
                    initialValue = valueOfInvestmentBeforeTransaction
                    initialValueWithCurrencyEffect = valueOfInvestmentBeforeTransactionWithCurrencyEffect
                elif (transactionInvestment > 0):
                    initialValue = transactionInvestment
                    initialValueWithCurrencyEffect = transactionInvestmentWithCurrencyEffect
            fees = (fees + (order.feeInBaseCurrency  or  0))
            feesWithCurrencyEffect = (feesWithCurrencyEffect + (order.feeInBaseCurrencyWithCurrencyEffect  or  0))
            totalUnits = (totalUnits + (order.quantity * getFactor(order.type)))
            valueOfInvestment = (totalUnits * marketPriceInBaseCurrency)
            valueOfInvestmentWithCurrencyEffect = (totalUnits * marketPriceInBaseCurrencyWithCurrencyEffect)
            grossPerformanceFromSell = (((order.unitPriceInBaseCurrency - lastAveragePrice) * order.quantity) if (order.type == 'SELL') else Decimal(str(0)))
            grossPerformanceFromSellWithCurrencyEffect = (((order.unitPriceInBaseCurrencyWithCurrencyEffect - lastAveragePriceWithCurrencyEffect) * order.quantity) if (order.type == 'SELL') else Decimal(str(0)))
            grossPerformanceFromSells = (grossPerformanceFromSells + grossPerformanceFromSell)
            grossPerformanceFromSellsWithCurrencyEffect = (grossPerformanceFromSellsWithCurrencyEffect + grossPerformanceFromSellWithCurrencyEffect)
            lastAveragePrice = (Decimal(str(0)) if (totalQuantityFromBuyTransactions == 0) else (totalInvestmentFromBuyTransactions / totalQuantityFromBuyTransactions))
            lastAveragePriceWithCurrencyEffect = (Decimal(str(0)) if (totalQuantityFromBuyTransactions == 0) else (totalInvestmentFromBuyTransactionsWithCurrencyEffect / totalQuantityFromBuyTransactions))
            if (totalUnits == 0):
                totalInvestmentFromBuyTransactions = Decimal(str(0))
                totalInvestmentFromBuyTransactionsWithCurrencyEffect = Decimal(str(0))
                totalQuantityFromBuyTransactions = Decimal(str(0))
            if PortfolioCalculator.ENABLE_LOGGING:
                print.log('grossPerformanceFromSells', float(grossPerformanceFromSells))
                print.log('grossPerformanceFromSellWithCurrencyEffect', float(grossPerformanceFromSellWithCurrencyEffect))
            newGrossPerformance = ((valueOfInvestment - totalInvestment) + grossPerformanceFromSells)
            newGrossPerformanceWithCurrencyEffect = ((valueOfInvestmentWithCurrencyEffect - totalInvestmentWithCurrencyEffect) + grossPerformanceFromSellsWithCurrencyEffect)
            grossPerformance = newGrossPerformance
            grossPerformanceWithCurrencyEffect = newGrossPerformanceWithCurrencyEffect
            if (order.itemType == 'start'):
                feesAtStartDate = fees
                feesAtStartDateWithCurrencyEffect = feesWithCurrencyEffect
                grossPerformanceAtStartDate = grossPerformance
                grossPerformanceAtStartDateWithCurrencyEffect = grossPerformanceWithCurrencyEffect
            if (i > indexOfStartOrder):
                if ((valueOfInvestmentBeforeTransaction > 0)  and  (order.type in ['BUY', 'SELL'])):
                    orderDate = _parse_date(order.date)
                    previousOrderDate = _parse_date(orders[(i - 1)].date)
                    daysSinceLastOrder = _difference_in_days(orderDate, previousOrderDate)
                    if (daysSinceLastOrder <= 0):
                        daysSinceLastOrder = float_info.epsilon
                    totalInvestmentDays += daysSinceLastOrder
                    sumOfTimeWeightedInvestments = (sumOfTimeWeightedInvestments + (((valueAtStartDate - investmentAtStartDate) + totalInvestmentBeforeTransaction) * daysSinceLastOrder))
                    sumOfTimeWeightedInvestmentsWithCurrencyEffect = (sumOfTimeWeightedInvestmentsWithCurrencyEffect + (((valueAtStartDateWithCurrencyEffect - investmentAtStartDateWithCurrencyEffect) + totalInvestmentBeforeTransactionWithCurrencyEffect) * daysSinceLastOrder))
                currentValues[order.date] = valueOfInvestment
                currentValuesWithCurrencyEffect[order.date] = valueOfInvestmentWithCurrencyEffect
                netPerformanceValues[order.date] = ((grossPerformance - grossPerformanceAtStartDate) - (fees - feesAtStartDate))
                netPerformanceValuesWithCurrencyEffect[order.date] = ((grossPerformanceWithCurrencyEffect - grossPerformanceAtStartDateWithCurrencyEffect) - (feesWithCurrencyEffect - feesAtStartDateWithCurrencyEffect))
                investmentValuesAccumulated[order.date] = totalInvestment
                investmentValuesAccumulatedWithCurrencyEffect[order.date] = totalInvestmentWithCurrencyEffect
                investmentValuesWithCurrencyEffect[order.date] = ((investmentValuesWithCurrencyEffect[order.date]  or  Decimal(str(0))) + transactionInvestmentWithCurrencyEffect)
                timeWeightedInvestmentValues[order.date] = ((sumOfTimeWeightedInvestments / totalInvestmentDays) if (totalInvestmentDays > float_info.epsilon) else (totalInvestment if (totalInvestment > 0) else Decimal(str(0))))
                timeWeightedInvestmentValuesWithCurrencyEffect[order.date] = ((sumOfTimeWeightedInvestmentsWithCurrencyEffect / totalInvestmentDays) if (totalInvestmentDays > float_info.epsilon) else (totalInvestmentWithCurrencyEffect if (totalInvestmentWithCurrencyEffect > 0) else Decimal(str(0))))
            if PortfolioCalculator.ENABLE_LOGGING:
                print.log('totalInvestment', float(totalInvestment))
                print.log('totalInvestmentWithCurrencyEffect', float(totalInvestmentWithCurrencyEffect))
                print.log('totalGrossPerformance', float((grossPerformance - grossPerformanceAtStartDate)))
                print.log('totalGrossPerformanceWithCurrencyEffect', float((grossPerformanceWithCurrencyEffect - grossPerformanceAtStartDateWithCurrencyEffect)))
            if (i == indexOfEndOrder):
                break
        totalGrossPerformance = (grossPerformance - grossPerformanceAtStartDate)
        totalGrossPerformanceWithCurrencyEffect = (grossPerformanceWithCurrencyEffect - grossPerformanceAtStartDateWithCurrencyEffect)
        totalNetPerformance = ((grossPerformance - grossPerformanceAtStartDate) - (fees - feesAtStartDate))
        timeWeightedAverageInvestmentBetweenStartAndEndDate = ((sumOfTimeWeightedInvestments / totalInvestmentDays) if (totalInvestmentDays > 0) else Decimal(str(0)))
        timeWeightedAverageInvestmentBetweenStartAndEndDateWithCurrencyEffect = ((sumOfTimeWeightedInvestmentsWithCurrencyEffect / totalInvestmentDays) if (totalInvestmentDays > 0) else Decimal(str(0)))
        grossPerformancePercentage = ((totalGrossPerformance / timeWeightedAverageInvestmentBetweenStartAndEndDate) if (timeWeightedAverageInvestmentBetweenStartAndEndDate > 0) else Decimal(str(0)))
        grossPerformancePercentageWithCurrencyEffect = ((totalGrossPerformanceWithCurrencyEffect / timeWeightedAverageInvestmentBetweenStartAndEndDateWithCurrencyEffect) if (timeWeightedAverageInvestmentBetweenStartAndEndDateWithCurrencyEffect > 0) else Decimal(str(0)))
        feesPerUnit = (((fees - feesAtStartDate) / totalUnits) if (totalUnits > 0) else Decimal(str(0)))
        feesPerUnitWithCurrencyEffect = (((feesWithCurrencyEffect - feesAtStartDateWithCurrencyEffect) / totalUnits) if (totalUnits > 0) else Decimal(str(0)))
        netPerformancePercentage = ((totalNetPerformance / timeWeightedAverageInvestmentBetweenStartAndEndDate) if (timeWeightedAverageInvestmentBetweenStartAndEndDate > 0) else Decimal(str(0)))
        netPerformancePercentageWithCurrencyEffectMap = {}
        netPerformanceWithCurrencyEffectMap = {}
        for dateRange in ['1d', '1y', '5y', 'max', 'mtd', 'wtd', 'ytd']:
            dateInterval = getIntervalFromDateRange(dateRange)
            endDate = dateInterval.endDate
            startDate = dateInterval.startDate
            if _is_before(startDate, start):
                startDate = start
            rangeEndDateString = _date_format(endDate, DATE_FORMAT)
            rangeStartDateString = _date_format(startDate, DATE_FORMAT)
            currentValuesAtDateRangeStartWithCurrencyEffect = (currentValuesWithCurrencyEffect[rangeStartDateString]  or  Decimal(str(0)))
            investmentValuesAccumulatedAtStartDateWithCurrencyEffect = (investmentValuesAccumulatedWithCurrencyEffect[rangeStartDateString]  or  Decimal(str(0)))
            grossPerformanceAtDateRangeStartWithCurrencyEffect = (currentValuesAtDateRangeStartWithCurrencyEffect - investmentValuesAccumulatedAtStartDateWithCurrencyEffect)
            average = Decimal(str(0))
            dayCount = 0
            i = (len(self.chart_dates) - 1)
            while (i >= 0):
                date = self.chart_dates[i]
                if (date > rangeEndDateString):
                    continue
                elif (date < rangeStartDateString):
                    break
                if (isinstance(investmentValuesAccumulatedWithCurrencyEffect[date], Big)  and  (investmentValuesAccumulatedWithCurrencyEffect[date] > 0)):
                    average = (average + (investmentValuesAccumulatedWithCurrencyEffect[date] + grossPerformanceAtDateRangeStartWithCurrencyEffect))
                    dayCount += 1
                i -= 1
            if (dayCount > 0):
                average = (average / dayCount)
            netPerformanceWithCurrencyEffectMap[dateRange] = ((netPerformanceValuesWithCurrencyEffect[rangeEndDateString] - (Decimal(str(0)) if (dateRange == 'max') else (netPerformanceValuesWithCurrencyEffect[rangeStartDateString]  or  Decimal(str(0)))))  or  Decimal(str(0)))
            netPerformancePercentageWithCurrencyEffectMap[dateRange] = ((netPerformanceWithCurrencyEffectMap[dateRange] / average) if (average > 0) else Decimal(str(0)))
        if PortfolioCalculator.ENABLE_LOGGING:
            pass

        {symbol}












        return {
            'currentValues': currentValues,
            'currentValuesWithCurrencyEffect': currentValuesWithCurrencyEffect,
            'feesWithCurrencyEffect': feesWithCurrencyEffect,
            'grossPerformancePercentage': grossPerformancePercentage,
            'grossPerformancePercentageWithCurrencyEffect': grossPerformancePercentageWithCurrencyEffect,
            'initialValue': initialValue,
            'initialValueWithCurrencyEffect': initialValueWithCurrencyEffect,
            'investmentValuesAccumulated': investmentValuesAccumulated,
            'investmentValuesAccumulatedWithCurrencyEffect': investmentValuesAccumulatedWithCurrencyEffect,
            'investmentValuesWithCurrencyEffect': investmentValuesWithCurrencyEffect,
            'netPerformancePercentage': netPerformancePercentage,
            'netPerformancePercentageWithCurrencyEffectMap': netPerformancePercentageWithCurrencyEffectMap,
            'netPerformanceValues': netPerformanceValues,
            'netPerformanceValuesWithCurrencyEffect': netPerformanceValuesWithCurrencyEffect,
            'netPerformanceWithCurrencyEffectMap': netPerformanceWithCurrencyEffectMap,
            'timeWeightedInvestmentValues': timeWeightedInvestmentValues,
            'timeWeightedInvestmentValuesWithCurrencyEffect': timeWeightedInvestmentValuesWithCurrencyEffect,
            'totalAccountBalanceInBaseCurrency': totalAccountBalanceInBaseCurrency,
            'totalDividend': totalDividend,
            'totalDividendInBaseCurrency': totalDividendInBaseCurrency,
            'totalInterest': totalInterest,
            'totalInterestInBaseCurrency': totalInterestInBaseCurrency,
            'totalInvestment': totalInvestment,
            'totalInvestmentWithCurrencyEffect': totalInvestmentWithCurrencyEffect,
            'totalLiabilities': totalLiabilities,
            'totalLiabilitiesInBaseCurrency': totalLiabilitiesInBaseCurrency,
            'grossPerformance': totalGrossPerformance,
            'grossPerformanceWithCurrencyEffect': totalGrossPerformanceWithCurrencyEffect,
            'hasErrors': ((totalUnits > 0)  and  (not initialValue  or  not unitPriceAtEndDate)),
            'netPerformance': totalNetPerformance,
            'timeWeightedInvestment': timeWeightedAverageInvestmentBetweenStartAndEndDate,
            'timeWeightedInvestmentWithCurrencyEffect': timeWeightedAverageInvestmentBetweenStartAndEndDateWithCurrencyEffect
        }

    def compute_snapshot(self):
        lastTransactionPoint = self.transaction_points[-1]
        transactionPoints = [x for x in self.transaction_points if _is_before(parseDate(x.get('date')), self.end_date)]
        if not len(transactionPoints):
            return {
                'activitiesCount': 0,
                'createdAt': datetime.now(),
                'currentValueInBaseCurrency': Decimal(str(0)),
                'errors': [],
                'hasErrors': False,
                'historicalData': [],
                'positions': [],
                'totalFeesWithCurrencyEffect': Decimal(str(0)),
                'totalInterestWithCurrencyEffect': Decimal(str(0)),
                'totalInvestment': Decimal(str(0)),
                'totalInvestmentWithCurrencyEffect': Decimal(str(0)),
                'totalLiabilitiesWithCurrencyEffect': Decimal(str(0))
            }
        currencies = {}
        dataGatheringItems = []
        firstIndex = len(transactionPoints)
        firstTransactionPoint = None
        totalInterestWithCurrencyEffect = Decimal(str(0))
        totalLiabilitiesWithCurrencyEffect = Decimal(str(0))
        for assetSubClass, currency, dataSource, symbol in transactionPoints[(firstIndex - 1)].items:
            if (assetSubClass != 'CASH'):
                dataGatheringItems.append({'dataSource': dataSource, 'symbol': symbol})
            currencies[symbol] = currency
        for i in range(len(transactionPoints)):
            if (not _is_before(parseDate(transactionPoints[i].date), self.start_date)  and  (firstTransactionPoint == None)):
                firstTransactionPoint = transactionPoints[i]
                firstIndex = i







        self.data_provider_infos = dataProviderInfos
        marketSymbolMap = {}
        for marketSymbol in marketSymbols:
            date = _date_format(marketSymbol.date, DATE_FORMAT)
            if not marketSymbolMap[date]:
                marketSymbolMap[date] = {}
            if marketSymbol.marketPrice:
                marketSymbolMap[date][marketSymbol.symbol] = Decimal(str(marketSymbol.marketPrice))
        endDateString = _date_format(self.end_date, DATE_FORMAT)
        daysInMarket = _difference_in_days(self.end_date, self.start_date)
        chartDateMap = self.get_chart_date_map({'endDate': self.end_date, 'startDate': self.start_date, 'step': Math.round((daysInMarket / _date_min(daysInMarket, self.configuration_service.get('MAX_CHART_ITEMS'))))})
        for accountBalanceItem in self.account_balance_items:
            chartDateMap[accountBalanceItem.date] = True
        chartDates = _sort_by(list(chartDateMap.keys()), lambda chartDate: chartDate)
        if (firstIndex > 0):
            firstIndex -= 1
        errors = []
        hasAnySymbolMetricsErrors = False
        positions = []
        accumulatedValuesByDate = {}
        valuesBySymbol = {}
        for item in lastTransactionPoint.items:
            marketPriceInBaseCurrency = ((marketSymbolMap[endDateString][item.symbol]  or  item.averagePrice) * (exchangeRatesByCurrency[f"{item.currency}{self.currency}"][endDateString]  or  1))
            currentValues, currentValuesWithCurrencyEffect, grossPerformance, grossPerformancePercentage, grossPerformancePercentageWithCurrencyEffect, grossPerformanceWithCurrencyEffect, hasErrors, investmentValuesAccumulated, investmentValuesAccumulatedWithCurrencyEffect, investmentValuesWithCurrencyEffect, netPerformance, netPerformancePercentage, netPerformancePercentageWithCurrencyEffectMap, netPerformanceValues, netPerformanceValuesWithCurrencyEffect, netPerformanceWithCurrencyEffectMap, timeWeightedInvestment, timeWeightedInvestmentValues, timeWeightedInvestmentValuesWithCurrencyEffect, timeWeightedInvestmentWithCurrencyEffect, totalDividend, totalDividendInBaseCurrency, totalInterestInBaseCurrency, totalInvestment, totalInvestmentWithCurrencyEffect, totalLiabilitiesInBaseCurrency = self.get_symbol_metrics({
                'chartDateMap': chartDateMap,
                'marketSymbolMap': marketSymbolMap,
                'dataSource': item.dataSource,
                'end': self.end_date,
                'exchangeRates': exchangeRatesByCurrency[f"{item.currency}{self.currency}"],
                'start': self.start_date,
                'symbol': item.symbol
            })
            hasAnySymbolMetricsErrors = (hasAnySymbolMetricsErrors  or  hasErrors)
            includeInTotalAssetValue = (item.assetSubClass != "CASH")
            if includeInTotalAssetValue:
                valuesBySymbol[item.symbol] = {
                    'currentValues': currentValues,
                    'currentValuesWithCurrencyEffect': currentValuesWithCurrencyEffect,
                    'investmentValuesAccumulated': investmentValuesAccumulated,
                    'investmentValuesAccumulatedWithCurrencyEffect': investmentValuesAccumulatedWithCurrencyEffect,
                    'investmentValuesWithCurrencyEffect': investmentValuesWithCurrencyEffect,
                    'netPerformanceValues': netPerformanceValues,
                    'netPerformanceValuesWithCurrencyEffect': netPerformanceValuesWithCurrencyEffect,
                    'timeWeightedInvestmentValues': timeWeightedInvestmentValues,
                    'timeWeightedInvestmentValuesWithCurrencyEffect': timeWeightedInvestmentValuesWithCurrencyEffect
                }
            positions.append({
                'includeInTotalAssetValue': includeInTotalAssetValue,
                'timeWeightedInvestment': timeWeightedInvestment,
                'timeWeightedInvestmentWithCurrencyEffect': timeWeightedInvestmentWithCurrencyEffect,
                'activitiesCount': item.activitiesCount,
                'averagePrice': item.averagePrice,
                'currency': item.currency,
                'dataSource': item.dataSource,
                'dateOfFirstActivity': item.dateOfFirstActivity,
                'dividend': totalDividend,
                'dividendInBaseCurrency': totalDividendInBaseCurrency,
                'fee': item.fee,
                'feeInBaseCurrency': item.feeInBaseCurrency,
                'grossPerformance': ((grossPerformance  or  None) if not hasErrors else None),
                'grossPerformancePercentage': ((grossPerformancePercentage  or  None) if not hasErrors else None),
                'grossPerformancePercentageWithCurrencyEffect': ((grossPerformancePercentageWithCurrencyEffect  or  None) if not hasErrors else None),
                'grossPerformanceWithCurrencyEffect': ((grossPerformanceWithCurrencyEffect  or  None) if not hasErrors else None),
                'includeInHoldings': item.includeInHoldings,
                'investment': totalInvestment,
                'investmentWithCurrencyEffect': totalInvestmentWithCurrencyEffect,
                'marketPrice': (float(marketSymbolMap[endDateString][item.symbol])  or  1),
                'marketPriceInBaseCurrency': (float(marketPriceInBaseCurrency)  or  1),
                'netPerformance': ((netPerformance  or  None) if not hasErrors else None),
                'netPerformancePercentage': ((netPerformancePercentage  or  None) if not hasErrors else None),
                'netPerformancePercentageWithCurrencyEffectMap': ((netPerformancePercentageWithCurrencyEffectMap  or  None) if not hasErrors else None),
                'netPerformanceWithCurrencyEffectMap': ((netPerformanceWithCurrencyEffectMap  or  None) if not hasErrors else None),
                'quantity': item.quantity,
                'symbol': item.symbol,
                'tags': item.tags,
                'valueInBaseCurrency': (Decimal(str(marketPriceInBaseCurrency)) * item.quantity)
            })
            totalInterestWithCurrencyEffect = (totalInterestWithCurrencyEffect + totalInterestInBaseCurrency)
            totalLiabilitiesWithCurrencyEffect = (totalLiabilitiesWithCurrencyEffect + totalLiabilitiesInBaseCurrency)
            if (((hasErrors  or  next((x for x in currentRateErrors if ((x.get('dataSource') == item.dataSource)  and  (x.get('symbol') == item.symbol))), None))  and  (item.investment > 0))  and  (item.skipErrors == False)):
                errors.append({'dataSource': item.dataSource, 'symbol': item.symbol})

        accountBalanceMap = {}
        lastKnownBalance = Decimal(str(0))
        for dateString in chartDates:
            if (accountBalanceItemsMap[dateString] != None):
                lastKnownBalance = accountBalanceItemsMap[dateString]
            accountBalanceMap[dateString] = lastKnownBalance
            for symbol in list(valuesBySymbol.keys()):
                symbolValues = valuesBySymbol[symbol]
                currentValue = (symbolValues.currentValues[dateString]  or  Decimal(str(0)))
                currentValueWithCurrencyEffect = (symbolValues.currentValuesWithCurrencyEffect[dateString]  or  Decimal(str(0)))
                investmentValueAccumulated = (symbolValues.investmentValuesAccumulated[dateString]  or  Decimal(str(0)))
                investmentValueAccumulatedWithCurrencyEffect = (symbolValues.investmentValuesAccumulatedWithCurrencyEffect[dateString]  or  Decimal(str(0)))
                investmentValueWithCurrencyEffect = (symbolValues.investmentValuesWithCurrencyEffect[dateString]  or  Decimal(str(0)))
                netPerformanceValue = (symbolValues.netPerformanceValues[dateString]  or  Decimal(str(0)))
                netPerformanceValueWithCurrencyEffect = (symbolValues.netPerformanceValuesWithCurrencyEffect[dateString]  or  Decimal(str(0)))
                timeWeightedInvestmentValue = (symbolValues.timeWeightedInvestmentValues[dateString]  or  Decimal(str(0)))
                timeWeightedInvestmentValueWithCurrencyEffect = (symbolValues.timeWeightedInvestmentValuesWithCurrencyEffect[dateString]  or  Decimal(str(0)))
                accumulatedValuesByDate[dateString] = {
                    'investmentValueWithCurrencyEffect': ((accumulatedValuesByDate[dateString].investmentValueWithCurrencyEffect  or  Decimal(str(0))) + investmentValueWithCurrencyEffect),
                    'totalAccountBalanceWithCurrencyEffect': accountBalanceMap[dateString],
                    'totalCurrentValue': ((accumulatedValuesByDate[dateString].totalCurrentValue  or  Decimal(str(0))) + currentValue),
                    'totalCurrentValueWithCurrencyEffect': ((accumulatedValuesByDate[dateString].totalCurrentValueWithCurrencyEffect  or  Decimal(str(0))) + currentValueWithCurrencyEffect),
                    'totalInvestmentValue': ((accumulatedValuesByDate[dateString].totalInvestmentValue  or  Decimal(str(0))) + investmentValueAccumulated),
                    'totalInvestmentValueWithCurrencyEffect': ((accumulatedValuesByDate[dateString].totalInvestmentValueWithCurrencyEffect  or  Decimal(str(0))) + investmentValueAccumulatedWithCurrencyEffect),
                    'totalNetPerformanceValue': ((accumulatedValuesByDate[dateString].totalNetPerformanceValue  or  Decimal(str(0))) + netPerformanceValue),
                    'totalNetPerformanceValueWithCurrencyEffect': ((accumulatedValuesByDate[dateString].totalNetPerformanceValueWithCurrencyEffect  or  Decimal(str(0))) + netPerformanceValueWithCurrencyEffect),
                    'totalTimeWeightedInvestmentValue': ((accumulatedValuesByDate[dateString].totalTimeWeightedInvestmentValue  or  Decimal(str(0))) + timeWeightedInvestmentValue),
                    'totalTimeWeightedInvestmentValueWithCurrencyEffect': ((accumulatedValuesByDate[dateString].totalTimeWeightedInvestmentValueWithCurrencyEffect  or  Decimal(str(0))) + timeWeightedInvestmentValueWithCurrencyEffect)
                }

        overall = self.calculate_overall_performance(positions)
        positionsIncludedInHoldings = [rest for x in [x for x in positions if x.get('includeInHoldings')]]
        return {
            **overall,
            'errors': errors,
            'historicalData': historicalData,
            'totalInterestWithCurrencyEffect': totalInterestWithCurrencyEffect,
            'totalLiabilitiesWithCurrencyEffect': totalLiabilitiesWithCurrencyEffect,
            'hasErrors': (hasAnySymbolMetricsErrors  or  overall.hasErrors),
            'positions': positionsIncludedInHoldings
        }


    def get_data_provider_infos(self):
        return self.data_provider_infos


    def get_dividend_in_base_currency(self):

        return getSum([x.get('dividendInBaseCurrency') for x in self.snapshot.positions])


    def get_fees_in_base_currency(self):

        return self.snapshot.totalFeesWithCurrencyEffect


    def get_interest_in_base_currency(self):

        return self.snapshot.totalInterestWithCurrencyEffect


    def get_investments(self):
        if (len(self.transaction_points) == 0):
            return []
        return [{'date': x.date, 'investment': functools.reduce(lambda investment, transactionPointSymbol: (investment + transactionPointSymbol.investment), x.items, Decimal(str(0)))} for x in self.transaction_points]


    def get_investments_by_group(self, data, groupBy):
        groupedData = {}
        for date, investmentValueWithCurrencyEffect in data:
            dateGroup = (date[0:7] if (groupBy == 'month') else date[0:4])
            groupedData[dateGroup] = ((groupedData[dateGroup]  or  Decimal(str(0))) + investmentValueWithCurrencyEffect)
        return [{'date': (f"{x}-01" if (groupBy == 'month') else f"{x}-01-01"), 'investment': float(groupedData[x])} for x in list(groupedData.keys())]


    def get_liabilities_in_base_currency(self):

        return self.snapshot.totalLiabilitiesWithCurrencyEffect


    def get_performance(self, end, start):

        historicalData = self.snapshot
        chart = []
        netPerformanceAtStartDate = None
        netPerformanceWithCurrencyEffectAtStartDate = None
        totalInvestmentValuesWithCurrencyEffect = []
        for historicalDataItem in historicalData:
            date = resetHours(parseDate(historicalDataItem.date))
            if (not _is_before(date, start)  and  not _is_after(date, end)):
                if not _is_number(netPerformanceAtStartDate):
                    netPerformanceAtStartDate = historicalDataItem.netPerformance
                    netPerformanceWithCurrencyEffectAtStartDate = historicalDataItem.netPerformanceWithCurrencyEffect
                netPerformanceSinceStartDate = (historicalDataItem.netPerformance - netPerformanceAtStartDate)
                netPerformanceWithCurrencyEffectSinceStartDate = (historicalDataItem.netPerformanceWithCurrencyEffect - netPerformanceWithCurrencyEffectAtStartDate)
                if (historicalDataItem.totalInvestmentValueWithCurrencyEffect > 0):
                    totalInvestmentValuesWithCurrencyEffect.append(historicalDataItem.totalInvestmentValueWithCurrencyEffect)
                timeWeightedInvestmentValue = ((sum(totalInvestmentValuesWithCurrencyEffect) / len(totalInvestmentValuesWithCurrencyEffect)) if (len(totalInvestmentValuesWithCurrencyEffect) > 0) else 0)
                chart.append({
                    **historicalDataItem,
                    'netPerformance': (historicalDataItem.netPerformance - netPerformanceAtStartDate),
                    'netPerformanceWithCurrencyEffect': netPerformanceWithCurrencyEffectSinceStartDate,
                    'netPerformanceInPercentage': (0 if (timeWeightedInvestmentValue == 0) else (netPerformanceSinceStartDate / timeWeightedInvestmentValue)),
                    'netPerformanceInPercentageWithCurrencyEffect': (0 if (timeWeightedInvestmentValue == 0) else (netPerformanceWithCurrencyEffectSinceStartDate / timeWeightedInvestmentValue))
                })
        return {'chart': chart}


    def get_start_date(self):
        firstAccountBalanceDate = None
        firstActivityDate = None
        try:
            firstAccountBalanceDateString = self.account_balance_items[0].date
            firstAccountBalanceDate = (parseDate(firstAccountBalanceDateString) if firstAccountBalanceDateString else datetime.now())
        except Exception as error:
            firstAccountBalanceDate = datetime.now()
        try:
            firstActivityDateString = self.transaction_points[0].date
            firstActivityDate = (parseDate(firstActivityDateString) if firstActivityDateString else datetime.now())
        except Exception as error:
            firstActivityDate = datetime.now()
        return _date_min([firstAccountBalanceDate, firstActivityDate])


    def get_transaction_points(self):
        return self.transaction_points


    def get_chart_date_map(self, endDate, startDate, step):

        for date in _each_day_of_interval({'end': endDate, 'start': startDate}, {'step': step}):
            chartDateMap[_date_format(date, DATE_FORMAT)] = True
        if (step > 1):
            for date in _each_day_of_interval({'end': endDate, 'start': _sub_days(endDate, 90)}, {'step': 3}):
                chartDateMap[_date_format(date, DATE_FORMAT)] = True
            for date in _each_day_of_interval({'end': endDate, 'start': _sub_days(endDate, 30)}, {'step': 1}):
                chartDateMap[_date_format(date, DATE_FORMAT)] = True
        chartDateMap[_date_format(endDate, DATE_FORMAT)] = True
        for dateRange in ['1d', '1y', '5y', 'max', 'mtd', 'wtd', 'ytd']:
            dateRangeEnd, dateRangeStart = getIntervalFromDateRange(dateRange)
            if (not _is_before(dateRangeStart, startDate)  and  not _is_after(dateRangeStart, endDate)):
                chartDateMap[_date_format(dateRangeStart, DATE_FORMAT)] = True
            if (not _is_before(dateRangeEnd, startDate)  and  not _is_after(dateRangeEnd, endDate)):
                chartDateMap[_date_format(dateRangeEnd, DATE_FORMAT)] = True
        interval = {'start': startDate, 'end': endDate}
        for date in _each_year_of_interval(interval):
            yearStart = _start_of_year(date)
            yearEnd = _end_of_year(date)
            if _is_within_interval(yearStart, interval):
                chartDateMap[_date_format(yearStart, DATE_FORMAT)] = True
            if _is_within_interval(yearEnd, interval):
                chartDateMap[_date_format(yearEnd, DATE_FORMAT)] = True
        return chartDateMap


    def compute_transaction_points(self):
        self.transaction_points = []
        symbols = {}
        lastDate = None
        lastTransactionPoint = None
        for date, fee, feeInBaseCurrency, quantity, SymbolProfile, tags, type, unitPrice in self.activities:
            currentTransactionPointItem = None
            assetSubClass = SymbolProfile.assetSubClass
            currency = SymbolProfile.currency
            dataSource = SymbolProfile.dataSource
            factor = getFactor(type)
            skipErrors = not not SymbolProfile.userId
            symbol = SymbolProfile.symbol
            oldAccumulatedSymbol = symbols[symbol]
            if oldAccumulatedSymbol:
                investment = oldAccumulatedSymbol.investment
                newQuantity = ((quantity * factor) + oldAccumulatedSymbol.quantity)
                if (type == 'BUY'):
                    if (oldAccumulatedSymbol.investment >= 0):
                        investment = (oldAccumulatedSymbol.investment + (quantity * unitPrice))
                    else:
                        investment = (oldAccumulatedSymbol.investment + (quantity * oldAccumulatedSymbol.averagePrice))
                elif (type == 'SELL'):
                    if (oldAccumulatedSymbol.investment > 0):
                        investment = (oldAccumulatedSymbol.investment - (quantity * oldAccumulatedSymbol.averagePrice))
                    else:
                        investment = (oldAccumulatedSymbol.investment - (quantity * unitPrice))
                if (abs(newQuantity) < float_info.epsilon):
                    investment = Decimal(str(0))
                    newQuantity = Decimal(str(0))
                currentTransactionPointItem = {
                    'assetSubClass': assetSubClass,
                    'currency': currency,
                    'dataSource': dataSource,
                    'investment': investment,
                    'skipErrors': skipErrors,
                    'symbol': symbol,
                    'activitiesCount': (oldAccumulatedSymbol.activitiesCount + 1),
                    'averagePrice': (Decimal(str(0)) if (newQuantity == 0) else abs((investment / newQuantity))),
                    'dateOfFirstActivity': oldAccumulatedSymbol.dateOfFirstActivity,
                    'dividend': Decimal(str(0)),
                    'fee': (oldAccumulatedSymbol.fee + fee),
                    'feeInBaseCurrency': (oldAccumulatedSymbol.feeInBaseCurrency + feeInBaseCurrency),
                    'includeInHoldings': oldAccumulatedSymbol.includeInHoldings,
                    'quantity': newQuantity,
                    'tags': [*oldAccumulatedSymbol.tags, *tags]
                }
            else:
                currentTransactionPointItem = {
                    'assetSubClass': assetSubClass,
                    'currency': currency,
                    'dataSource': dataSource,
                    'fee': fee,
                    'feeInBaseCurrency': feeInBaseCurrency,
                    'skipErrors': skipErrors,
                    'symbol': symbol,
                    'tags': tags,
                    'activitiesCount': 1,
                    'averagePrice': unitPrice,
                    'dateOfFirstActivity': date,
                    'dividend': Decimal(str(0)),
                    'includeInHoldings': (type in ['BUY', 'DIVIDEND', 'SELL']),
                    'investment': ((unitPrice * quantity) * factor),
                    'quantity': (quantity * factor)
                }
            currentTransactionPointItem.tags = _uniq_by(currentTransactionPointItem.tags, 'id')
            symbols[SymbolProfile.symbol] = currentTransactionPointItem
            items = (lastTransactionPoint.items  or  [])
            newItems = [x for x in items if (x.get('symbol') != SymbolProfile.symbol)]
            newItems.append(currentTransactionPointItem)
            sorted(newItems, key=functools.cmp_to_key(lambda a, b: ((a.symbol > b.symbol) - (a.symbol < b.symbol))))
            fees = Decimal(str(0))
            if (type == 'FEE'):
                fees = fee
            interest = Decimal(str(0))
            if (type == 'INTEREST'):
                interest = (quantity * unitPrice)
            liabilities = Decimal(str(0))
            if (type == 'LIABILITY'):
                liabilities = (quantity * unitPrice)
            if ((lastDate != date)  or  (lastTransactionPoint == None)):
                lastTransactionPoint = {
                    'date': date,
                    'fees': fees,
                    'interest': interest,
                    'liabilities': liabilities,
                    'items': newItems
                }
                self.transaction_points.append(lastTransactionPoint)
            else:
                lastTransactionPoint.fees = (lastTransactionPoint.fees + fees)
                lastTransactionPoint.interest = (lastTransactionPoint.interest + interest)
                lastTransactionPoint.items = newItems
                lastTransactionPoint.liabilities = (lastTransactionPoint.liabilities + liabilities)
            lastDate = date


    def _get_snapshot_cached(self):
        if not hasattr(self, '_snapshot'):
            try:
                self._snapshot = self.compute_snapshot()
            except Exception:
                self._snapshot = None
        return self._snapshot

    def get_performance(self):
        activities = self.sorted_activities()
        first_date = min((a["date"] for a in activities), default=None)
        snapshot = self._get_snapshot_cached()
        if not snapshot:
            return {"chart": [], "firstOrderDate": first_date, "performance": {
                "currentNetWorth": 0, "currentValue": 0,
                "currentValueInBaseCurrency": 0, "netPerformance": 0,
                "netPerformancePercentage": 0,
                "netPerformancePercentageWithCurrencyEffect": 0,
                "netPerformanceWithCurrencyEffect": 0,
                "totalFees": 0, "totalInvestment": 0,
                "totalLiabilities": 0.0, "totalValueables": 0.0,
            }}
        hist = snapshot.get("historicalData", [])
        positions = snapshot.get("positions", [])
        chart = []
        np_start = None
        np_ce_start = None
        twi_vals = []
        for item in hist:
            if np_start is None:
                np_start = item.get("netPerformance", 0)
                np_ce_start = item.get("netPerformanceWithCurrencyEffect", 0)
            np_since = item.get("netPerformance", 0) - np_start
            np_ce_since = item.get("netPerformanceWithCurrencyEffect", 0) - np_ce_start
            if item.get("totalInvestmentValueWithCurrencyEffect", 0) > 0:
                twi_vals.append(item["totalInvestmentValueWithCurrencyEffect"])
            twi_avg = sum(twi_vals) / len(twi_vals) if twi_vals else 0
            chart.append({**item,
                "netPerformance": np_since,
                "netPerformanceWithCurrencyEffect": np_ce_since,
                "netPerformanceInPercentage": np_since / twi_avg if twi_avg else 0,
                "netPerformanceInPercentageWithCurrencyEffect": np_ce_since / twi_avg if twi_avg else 0,
            })
        total_inv = sum(float(p.get("investment", 0)) for p in positions if p.get("includeInTotalAssetValue", True))
        current_val = sum(float(p.get("valueInBaseCurrency", 0)) for p in positions if p.get("includeInTotalAssetValue", True))
        total_fees = float(snapshot.get("totalFeesWithCurrencyEffect", 0))
        net_perf = sum(float(p.get("netPerformance", 0) or 0) for p in positions if p.get("includeInTotalAssetValue", True))
        return {"chart": chart, "firstOrderDate": first_date, "performance": {
            "currentNetWorth": current_val,
            "currentValue": current_val,
            "currentValueInBaseCurrency": current_val,
            "netPerformance": net_perf,
            "netPerformancePercentage": 0,
            "netPerformancePercentageWithCurrencyEffect": 0,
            "netPerformanceWithCurrencyEffect": net_perf,
            "totalFees": total_fees,
            "totalInvestment": total_inv,
            "totalLiabilities": 0.0,
            "totalValueables": 0.0,
        }}

    def get_investments(self, group_by=None):
        snapshot = self._get_snapshot_cached()
        if not snapshot:
            return {"investments": []}
        hist = snapshot.get("historicalData", [])
        if group_by:
            grouped = {}
            for item in hist:
                d = item["date"]
                inv = item.get("investmentValueWithCurrencyEffect", 0)
                key = d[:7] if group_by == "month" else d[:4]
                grouped[key] = grouped.get(key, 0) + inv
            investments = []
            for key in sorted(grouped.keys()):
                dt = f"{key}-01" if group_by == "month" else f"{key}-01-01"
                investments.append({"date": dt, "investment": grouped[key]})
            return {"investments": investments}
        tp = self._compute_tp()
        investments = []
        for t in tp:
            total_inv = sum(float(it.get("investment", 0)) for it in t["items"])
            investments.append({"date": t["date"], "investment": total_inv})
        return {"investments": investments}

    def get_holdings(self):
        snapshot = self._get_snapshot_cached()
        if not snapshot:
            return {"holdings": {}}
        holdings = {}
        for pos in snapshot.get("positions", []):
            sym = pos.get("symbol", "")
            qty = pos.get("quantity", 0)
            if isinstance(qty, Decimal):
                qty = float(qty)
            if qty == 0:
                continue
            h = {}
            for k, v in pos.items():
                if isinstance(v, Decimal):
                    h[k] = float(v)
                elif isinstance(v, dict):
                    h[k] = {dk: float(dv) if isinstance(dv, Decimal) else dv for dk, dv in v.items()}
                else:
                    h[k] = v
            holdings[sym] = h
        return {"holdings": holdings}

    def get_details(self, base_currency="USD"):
        snapshot = self._get_snapshot_cached()
        if not snapshot:
            return {"accounts": {}, "createdAt": None, "holdings": {},
                    "platforms": {}, "summary": {"totalInvestment": 0,
                    "netPerformance": 0, "currentValueInBaseCurrency": 0},
                    "hasError": False}
        holdings_data = self.get_holdings()
        positions = snapshot.get("positions", [])
        total_inv = sum(float(p.get("investment", 0)) for p in positions)
        current_val = sum(float(p.get("valueInBaseCurrency", 0)) for p in positions)
        net_perf = sum(float(p.get("netPerformance", 0) or 0) for p in positions)
        total_fees = float(snapshot.get("totalFeesWithCurrencyEffect", 0))
        activities = self.sorted_activities()
        created_at = min((a["date"] for a in activities), default=None)
        return {"accounts": {"default": {"balance": 0.0, "currency": base_currency,
            "name": "Default Account", "valueInBaseCurrency": current_val}},
            "createdAt": created_at, "holdings": holdings_data.get("holdings", {}),
            "platforms": {"default": {"balance": 0.0, "currency": base_currency,
            "name": "Default Platform", "valueInBaseCurrency": current_val}},
            "summary": {"totalInvestment": total_inv, "netPerformance": net_perf,
            "currentValueInBaseCurrency": current_val, "totalFees": total_fees},
            "hasError": snapshot.get("hasErrors", False)}

    def get_dividends(self, group_by=None):
        activities = self.sorted_activities()
        dividends = [a for a in activities if a.get("type") == "DIVIDEND"]
        if group_by:
            grouped = {}
            for div in dividends:
                d = div["date"]
                amount = float(div.get("quantity", 0)) * float(div.get("unitPrice", 0))
                key = d[:7] if group_by == "month" else d[:4]
                grouped[key] = grouped.get(key, 0) + amount
            result = []
            for key in sorted(grouped.keys()):
                dt = f"{key}-01" if group_by == "month" else f"{key}-01-01"
                result.append({"date": dt, "investment": grouped[key]})
            return {"dividends": result}
        result = []
        for div in dividends:
            amount = float(div.get("quantity", 0)) * float(div.get("unitPrice", 0))
            result.append({"date": div["date"], "investment": amount})
        return {"dividends": result}

    def evaluate_report(self):
        return {"xRay": {"categories": [
            {"key": "accounts", "name": "Accounts", "rules": []},
            {"key": "currencies", "name": "Currencies", "rules": []},
            {"key": "fees", "name": "Fees", "rules": []},
        ], "statistics": {"rulesActiveCount": 0, "rulesFulfilledCount": 0}}}

    def _compute_tp(self):
        if not hasattr(self, "_tp_cache"):
            self._tp_cache = self.compute_transaction_points() if hasattr(self, "compute_transaction_points") else []
        return self._tp_cache
