"""ROAI Portfolio Calculator — translated from TypeScript.

Generated by tt from:
  apps/api/src/app/portfolio/calculator/roai/portfolio-calculator.ts
  apps/api/src/app/portfolio/calculator/portfolio-calculator.ts
"""
from __future__ import annotations

import copy
import functools
from datetime import datetime, timedelta, date
from decimal import Decimal
from sys import float_info

from app.wrapper.portfolio.calculator.portfolio_calculator import PortfolioCalculator
from app.wrapper.portfolio.current_rate_service import CurrentRateService
from app.implementation.portfolio.calculator.helpers import (
    DATE_FORMAT, get_factor, get_sum, parse_date, reset_hours,
    get_interval_from_date_range, _date_format, _is_before, _is_after,
    _difference_in_days, _add_milliseconds, _sub_days, _each_day_of_interval,
    _each_year_of_interval, _start_of_day, _end_of_day, _start_of_year,
    _end_of_year, _is_within_interval, _date_min, _is_this_year, _is_number,
    _sort_by, _uniq_by, _to_date, _to_datetime,
)

class RoaiPortfolioCalculator(PortfolioCalculator):


    # --- Interface methods (translated from base calculator) ---

    def _build_market_symbol_map(self):
        """Build market symbol map from current_rate_service."""
        activities = self.sorted_activities()
        if not activities:
            return {}, set()

        symbols = set()
        for act in activities:
            sym = act.get('symbol', '')
            if sym:
                symbols.add(sym)

        first_date = min(a['date'] for a in activities)
        today = date.today().isoformat()
        all_dates = self.current_rate_service.all_dates_in_range(first_date, today)
        all_dates.add(first_date)
        all_dates.add(today)

        market_map = {}
        for d in sorted(all_dates):
            market_map[d] = {}
            for sym in symbols:
                price = self.current_rate_service.get_price(sym, d)
                if price is not None:
                    market_map[d][sym] = Decimal(str(price))

        return market_map, symbols

    def _compute_transaction_points(self):
        """Compute transaction points from activities (translated from base calculator)."""
        activities = self.sorted_activities()
        transaction_points = []
        symbols = {}
        last_date = None
        last_tp = None

        for act in activities:
            act_date = act['date']
            symbol = act.get('symbol', '')
            act_type = act.get('type', '')
            quantity = Decimal(str(act.get('quantity', 0)))
            unit_price = Decimal(str(act.get('unitPrice', 0)))
            fee = Decimal(str(act.get('fee', 0)))
            data_source = act.get('dataSource', 'YAHOO')
            currency = act.get('currency', 'USD')
            factor = get_factor(act_type)

            old = symbols.get(symbol)
            if old:
                investment = old['investment']
                new_qty = quantity * factor + old['quantity']

                if act_type == 'BUY':
                    if old['investment'] >= 0:
                        investment = old['investment'] + quantity * unit_price
                    else:
                        investment = old['investment'] + quantity * old['averagePrice']
                elif act_type == 'SELL':
                    if old['investment'] > 0:
                        investment = old['investment'] - quantity * old['averagePrice']
                    else:
                        investment = old['investment'] - quantity * unit_price

                if abs(new_qty) < Decimal('1e-10'):
                    investment = Decimal('0')
                    new_qty = Decimal('0')

                avg_price = Decimal('0') if new_qty == 0 else abs(investment / new_qty)

                current_item = {
                    'symbol': symbol,
                    'currency': currency,
                    'dataSource': data_source,
                    'quantity': new_qty,
                    'investment': investment,
                    'averagePrice': avg_price,
                    'fee': old['fee'] + fee,
                    'feeInBaseCurrency': old.get('feeInBaseCurrency', Decimal('0')) + fee,
                    'dateOfFirstActivity': old['dateOfFirstActivity'],
                    'activitiesCount': old['activitiesCount'] + 1,
                    'assetSubClass': old.get('assetSubClass'),
                    'includeInHoldings': old.get('includeInHoldings', True),
                    'skipErrors': False,
                    'tags': [],
                }
            else:
                current_item = {
                    'symbol': symbol,
                    'currency': currency,
                    'dataSource': data_source,
                    'quantity': quantity * factor,
                    'investment': unit_price * quantity * factor,
                    'averagePrice': unit_price,
                    'fee': fee,
                    'feeInBaseCurrency': fee,
                    'dateOfFirstActivity': act_date,
                    'activitiesCount': 1,
                    'assetSubClass': act.get('assetSubClass'),
                    'includeInHoldings': act_type in ['BUY', 'DIVIDEND', 'SELL'],
                    'skipErrors': False,
                    'tags': [],
                }

            symbols[symbol] = current_item

            new_items = [v for k, v in symbols.items()]
            new_items.sort(key=lambda x: x.get('symbol', ''))

            if last_date != act_date or last_tp is None:
                last_tp = {'date': act_date, 'items': new_items}
                transaction_points.append(last_tp)
            else:
                last_tp['items'] = new_items

            last_date = act_date

        return transaction_points

    def _compute_snapshot(self):
        """Compute full portfolio snapshot (translated from base calculator)."""
        transaction_points = self._compute_transaction_points()
        if not transaction_points:
            return {
                'activitiesCount': 0,
                'currentValueInBaseCurrency': Decimal('0'),
                'errors': [],
                'hasErrors': False,
                'historicalData': [],
                'positions': [],
                'totalFeesWithCurrencyEffect': Decimal('0'),
                'totalInterestWithCurrencyEffect': Decimal('0'),
                'totalInvestment': Decimal('0'),
                'totalInvestmentWithCurrencyEffect': Decimal('0'),
                'totalLiabilitiesWithCurrencyEffect': Decimal('0'),
            }

        market_map, all_symbols = self._build_market_symbol_map()
        last_tp = transaction_points[-1]
        today = date.today().isoformat()

        first_date = transaction_points[0]['date']
        interval = get_interval_from_date_range('max', first_date)
        start_date = interval['start_date']
        end_date = interval['end_date']
        start_str = start_date.isoformat() if hasattr(start_date, 'isoformat') else str(start_date)
        end_str = end_date.isoformat() if hasattr(end_date, 'isoformat') else str(end_date)

        # Build chart date map
        chart_date_map = {}
        for tp in transaction_points:
            chart_date_map[tp['date']] = True
        for d in sorted(market_map.keys()):
            if start_str <= d <= end_str:
                chart_date_map[d] = True
        chart_date_map[end_str] = True

        # Exchange rates: 1.0 for single-currency
        exchange_rates = {}
        for d in sorted(chart_date_map.keys()):
            exchange_rates[d] = 1.0

        positions = []
        values_by_symbol = {}
        has_any_errors = False

        for item in last_tp['items']:
            sym = item['symbol']
            result = self.get_symbol_metrics(
                chartDateMap=chart_date_map,
                dataSource=item.get('dataSource', 'YAHOO'),
                end=end_date,
                exchangeRates=exchange_rates,
                marketSymbolMap=market_map,
                start=start_date,
                symbol=sym,
            )

            if isinstance(result, dict):
                has_errors = result.get('hasErrors', False)
                has_any_errors = has_any_errors or has_errors

                # Get market price
                market_price = Decimal('0')
                if end_str in market_map and sym in market_map[end_str]:
                    market_price = market_map[end_str][sym]
                elif not market_price:
                    market_price = Decimal(str(
                        self.current_rate_service.get_latest_price(sym) or 0
                    ))

                total_investment = result.get('totalInvestment', Decimal('0'))
                net_perf = result.get('netPerformance', Decimal('0'))
                gross_perf = result.get('grossPerformance', Decimal('0'))

                position = {
                    'symbol': sym,
                    'currency': item.get('currency', 'USD'),
                    'dataSource': item.get('dataSource', 'YAHOO'),
                    'quantity': item['quantity'],
                    'investment': total_investment,
                    'investmentWithCurrencyEffect': result.get('totalInvestmentWithCurrencyEffect', total_investment),
                    'marketPrice': float(market_price),
                    'marketPriceInBaseCurrency': float(market_price),
                    'valueInBaseCurrency': market_price * item['quantity'],
                    'grossPerformance': gross_perf if not has_errors else None,
                    'grossPerformanceWithCurrencyEffect': result.get('grossPerformanceWithCurrencyEffect', gross_perf) if not has_errors else None,
                    'grossPerformancePercentage': result.get('grossPerformancePercentage', Decimal('0')) if not has_errors else None,
                    'grossPerformancePercentageWithCurrencyEffect': result.get('grossPerformancePercentageWithCurrencyEffect', Decimal('0')) if not has_errors else None,
                    'netPerformance': net_perf if not has_errors else None,
                    'netPerformancePercentage': result.get('netPerformancePercentage', Decimal('0')) if not has_errors else None,
                    'netPerformancePercentageWithCurrencyEffectMap': result.get('netPerformancePercentageWithCurrencyEffectMap', {}) if not has_errors else None,
                    'netPerformanceWithCurrencyEffectMap': result.get('netPerformanceWithCurrencyEffectMap', {}) if not has_errors else None,
                    'fee': item.get('fee', Decimal('0')),
                    'feeInBaseCurrency': item.get('feeInBaseCurrency', Decimal('0')),
                    'dividend': result.get('totalDividend', Decimal('0')),
                    'dividendInBaseCurrency': result.get('totalDividendInBaseCurrency', Decimal('0')),
                    'dateOfFirstActivity': item.get('dateOfFirstActivity'),
                    'activitiesCount': item.get('activitiesCount', 0),
                    'averagePrice': item.get('averagePrice', Decimal('0')),
                    'timeWeightedInvestment': result.get('timeWeightedInvestment', Decimal('0')),
                    'timeWeightedInvestmentWithCurrencyEffect': result.get('timeWeightedInvestmentWithCurrencyEffect', Decimal('0')),
                    'includeInTotalAssetValue': item.get('assetSubClass') != 'CASH',
                    'tags': item.get('tags', []),
                }
                positions.append(position)

                values_by_symbol[sym] = {
                    'currentValues': result.get('currentValues', {}),
                    'currentValuesWithCurrencyEffect': result.get('currentValuesWithCurrencyEffect', {}),
                    'investmentValuesAccumulated': result.get('investmentValuesAccumulated', {}),
                    'investmentValuesAccumulatedWithCurrencyEffect': result.get('investmentValuesAccumulatedWithCurrencyEffect', {}),
                    'investmentValuesWithCurrencyEffect': result.get('investmentValuesWithCurrencyEffect', {}),
                    'netPerformanceValues': result.get('netPerformanceValues', {}),
                    'netPerformanceValuesWithCurrencyEffect': result.get('netPerformanceValuesWithCurrencyEffect', {}),
                    'timeWeightedInvestmentValues': result.get('timeWeightedInvestmentValues', {}),
                    'timeWeightedInvestmentValuesWithCurrencyEffect': result.get('timeWeightedInvestmentValuesWithCurrencyEffect', {}),
                }

        # Build historical data
        chart_dates = sorted(chart_date_map.keys())
        accumulated = {}
        for d in chart_dates:
            if d < start_str or d > end_str:
                continue
            for sym, sv in values_by_symbol.items():
                cv = sv['currentValues'].get(d, Decimal('0'))
                cv_ce = sv['currentValuesWithCurrencyEffect'].get(d, Decimal('0'))
                iv = sv['investmentValuesAccumulated'].get(d, Decimal('0'))
                iv_ce = sv['investmentValuesAccumulatedWithCurrencyEffect'].get(d, Decimal('0'))
                inv_ce = sv['investmentValuesWithCurrencyEffect'].get(d, Decimal('0'))
                np_val = sv['netPerformanceValues'].get(d, Decimal('0'))
                np_ce = sv['netPerformanceValuesWithCurrencyEffect'].get(d, Decimal('0'))
                twi = sv['timeWeightedInvestmentValues'].get(d, Decimal('0'))
                twi_ce = sv['timeWeightedInvestmentValuesWithCurrencyEffect'].get(d, Decimal('0'))

                if d not in accumulated:
                    accumulated[d] = {
                        'totalCurrentValue': Decimal('0'),
                        'totalCurrentValueWithCurrencyEffect': Decimal('0'),
                        'totalInvestmentValue': Decimal('0'),
                        'totalInvestmentValueWithCurrencyEffect': Decimal('0'),
                        'investmentValueWithCurrencyEffect': Decimal('0'),
                        'totalNetPerformanceValue': Decimal('0'),
                        'totalNetPerformanceValueWithCurrencyEffect': Decimal('0'),
                        'totalTimeWeightedInvestmentValue': Decimal('0'),
                        'totalTimeWeightedInvestmentValueWithCurrencyEffect': Decimal('0'),
                    }
                acc = accumulated[d]
                acc['totalCurrentValue'] += cv
                acc['totalCurrentValueWithCurrencyEffect'] += cv_ce
                acc['totalInvestmentValue'] += iv
                acc['totalInvestmentValueWithCurrencyEffect'] += iv_ce
                acc['investmentValueWithCurrencyEffect'] += inv_ce
                acc['totalNetPerformanceValue'] += np_val
                acc['totalNetPerformanceValueWithCurrencyEffect'] += np_ce
                acc['totalTimeWeightedInvestmentValue'] += twi
                acc['totalTimeWeightedInvestmentValueWithCurrencyEffect'] += twi_ce

        historical_data = []
        for d in sorted(accumulated.keys()):
            v = accumulated[d]
            twi_val = v['totalTimeWeightedInvestmentValue']
            twi_ce_val = v['totalTimeWeightedInvestmentValueWithCurrencyEffect']
            np_pct = 0 if twi_val == 0 else float(v['totalNetPerformanceValue'] / twi_val)
            np_pct_ce = 0 if twi_ce_val == 0 else float(v['totalNetPerformanceValueWithCurrencyEffect'] / twi_ce_val)

            historical_data.append({
                'date': d,
                'investmentValueWithCurrencyEffect': float(v['investmentValueWithCurrencyEffect']),
                'netPerformance': float(v['totalNetPerformanceValue']),
                'netPerformanceWithCurrencyEffect': float(v['totalNetPerformanceValueWithCurrencyEffect']),
                'netPerformanceInPercentage': np_pct,
                'netPerformanceInPercentageWithCurrencyEffect': np_pct_ce,
                'totalAccountBalance': 0,
                'totalInvestment': float(v['totalInvestmentValue']),
                'totalInvestmentValueWithCurrencyEffect': float(v['totalInvestmentValueWithCurrencyEffect']),
                'value': float(v['totalCurrentValue']),
                'valueWithCurrencyEffect': float(v['totalCurrentValueWithCurrencyEffect']),
                'netWorth': float(v['totalCurrentValueWithCurrencyEffect']),
            })

        # Calculate overall performance
        overall = self.calculate_overall_performance(positions)

        return {
            **overall,
            'errors': [],
            'historicalData': historical_data,
            'hasErrors': has_any_errors or overall.get('hasErrors', False),
            'positions': positions,
        }

    def get_performance(self):
        """Return full performance response."""
        snapshot = self._compute_snapshot()
        activities = self.sorted_activities()
        first_date = min((a['date'] for a in activities), default=None)

        # Filter chart data
        chart = snapshot.get('historicalData', [])

        # Calculate net performance from chart
        net_perf_start = None
        net_perf_ce_start = None
        result_chart = []
        twi_values = []

        for item in chart:
            if net_perf_start is None:
                net_perf_start = item.get('netPerformance', 0)
                net_perf_ce_start = item.get('netPerformanceWithCurrencyEffect', 0)

            np_since_start = item.get('netPerformance', 0) - net_perf_start
            np_ce_since_start = item.get('netPerformanceWithCurrencyEffect', 0) - net_perf_ce_start

            if item.get('totalInvestmentValueWithCurrencyEffect', 0) > 0:
                twi_values.append(item['totalInvestmentValueWithCurrencyEffect'])

            twi_avg = sum(twi_values) / len(twi_values) if twi_values else 0

            result_chart.append({
                **item,
                'netPerformance': np_since_start,
                'netPerformanceWithCurrencyEffect': np_ce_since_start,
                'netPerformanceInPercentage': np_since_start / twi_avg if twi_avg else 0,
                'netPerformanceInPercentageWithCurrencyEffect': np_ce_since_start / twi_avg if twi_avg else 0,
            })

        # Compute summary from positions
        total_investment = Decimal('0')
        current_value = Decimal('0')
        total_fees = Decimal('0')
        net_performance = Decimal('0')
        net_perf_pct = Decimal('0')
        net_perf_pct_ce = Decimal('0')
        total_liabilities = Decimal('0')

        for pos in snapshot.get('positions', []):
            if pos.get('includeInTotalAssetValue', True):
                inv = pos.get('investment', Decimal('0'))
                if isinstance(inv, (int, float)):
                    inv = Decimal(str(inv))
                total_investment += inv
                vib = pos.get('valueInBaseCurrency', Decimal('0'))
                if isinstance(vib, (int, float)):
                    vib = Decimal(str(vib))
                current_value += vib
                fee = pos.get('feeInBaseCurrency', Decimal('0'))
                if isinstance(fee, (int, float)):
                    fee = Decimal(str(fee))
                total_fees += fee
                np_val = pos.get('netPerformance')
                if np_val is not None:
                    if isinstance(np_val, (int, float)):
                        np_val = Decimal(str(np_val))
                    net_performance += np_val

        net_worth = float(current_value)

        # Get net performance percentage from positions
        for pos in snapshot.get('positions', []):
            np_pct_map = pos.get('netPerformancePercentageWithCurrencyEffectMap')
            if np_pct_map and isinstance(np_pct_map, dict):
                max_val = np_pct_map.get('max', Decimal('0'))
                if isinstance(max_val, (int, float)):
                    max_val = Decimal(str(max_val))
                net_perf_pct_ce += max_val

        return {
            'chart': result_chart,
            'firstOrderDate': first_date,
            'performance': {
                'currentNetWorth': net_worth,
                'currentValue': float(current_value),
                'currentValueInBaseCurrency': float(current_value),
                'netPerformance': float(net_performance),
                'netPerformancePercentage': float(net_perf_pct),
                'netPerformancePercentageWithCurrencyEffect': float(net_perf_pct_ce),
                'netPerformanceWithCurrencyEffect': float(net_performance),
                'totalFees': float(total_fees),
                'totalInvestment': float(total_investment),
                'totalLiabilities': float(total_liabilities),
                'totalValueables': 0.0,
            },
        }

    def get_investments(self, group_by=None):
        """Return investments timeline."""
        transaction_points = self._compute_transaction_points()
        if not transaction_points:
            return {'investments': []}

        if group_by:
            # Group by month or year
            snapshot = self._compute_snapshot()
            hist_data = snapshot.get('historicalData', [])
            grouped = {}
            for item in hist_data:
                d = item['date']
                inv = item.get('investmentValueWithCurrencyEffect', 0)
                if group_by == 'month':
                    key = d[:7]
                else:
                    key = d[:4]
                grouped[key] = grouped.get(key, 0) + inv

            investments = []
            for key in sorted(grouped.keys()):
                if group_by == 'month':
                    investments.append({'date': f'{key}-01', 'investment': grouped[key]})
                else:
                    investments.append({'date': f'{key}-01-01', 'investment': grouped[key]})
            return {'investments': investments}

        investments = []
        for tp in transaction_points:
            total_inv = Decimal('0')
            for item in tp['items']:
                total_inv += item.get('investment', Decimal('0'))
            investments.append({
                'date': tp['date'],
                'investment': float(total_inv),
            })
        return {'investments': investments}

    def get_holdings(self):
        """Return holdings per symbol."""
        snapshot = self._compute_snapshot()
        holdings = {}

        for pos in snapshot.get('positions', []):
            sym = pos['symbol']
            qty = pos.get('quantity', Decimal('0'))
            if isinstance(qty, Decimal) and qty == 0:
                continue

            holdings[sym] = {
                'symbol': sym,
                'currency': pos.get('currency', 'USD'),
                'dataSource': pos.get('dataSource', 'YAHOO'),
                'quantity': float(qty),
                'investment': float(pos.get('investment', 0)),
                'marketPrice': pos.get('marketPrice', 0),
                'marketPriceInBaseCurrency': pos.get('marketPriceInBaseCurrency', 0),
                'valueInBaseCurrency': float(pos.get('valueInBaseCurrency', 0)),
                'grossPerformance': float(pos['grossPerformance']) if pos.get('grossPerformance') is not None else None,
                'grossPerformancePercentage': float(pos['grossPerformancePercentage']) if pos.get('grossPerformancePercentage') is not None else None,
                'grossPerformancePercentageWithCurrencyEffect': float(pos['grossPerformancePercentageWithCurrencyEffect']) if pos.get('grossPerformancePercentageWithCurrencyEffect') is not None else None,
                'grossPerformanceWithCurrencyEffect': float(pos['grossPerformanceWithCurrencyEffect']) if pos.get('grossPerformanceWithCurrencyEffect') is not None else None,
                'netPerformance': float(pos['netPerformance']) if pos.get('netPerformance') is not None else None,
                'netPerformancePercentage': float(pos['netPerformancePercentage']) if pos.get('netPerformancePercentage') is not None else None,
                'netPerformancePercentageWithCurrencyEffectMap': {k: float(v) for k, v in pos.get('netPerformancePercentageWithCurrencyEffectMap', {}).items()} if pos.get('netPerformancePercentageWithCurrencyEffectMap') else {},
                'netPerformanceWithCurrencyEffectMap': {k: float(v) for k, v in pos.get('netPerformanceWithCurrencyEffectMap', {}).items()} if pos.get('netPerformanceWithCurrencyEffectMap') else {},
                'averagePrice': float(pos.get('averagePrice', 0)),
                'fee': float(pos.get('fee', 0)),
                'feeInBaseCurrency': float(pos.get('feeInBaseCurrency', 0)),
                'dividend': float(pos.get('dividend', 0)),
                'dividendInBaseCurrency': float(pos.get('dividendInBaseCurrency', 0)),
                'dateOfFirstActivity': pos.get('dateOfFirstActivity'),
                'activitiesCount': pos.get('activitiesCount', 0),
                'tags': pos.get('tags', []),
            }

        return {'holdings': holdings}

    def get_details(self, base_currency='USD'):
        """Return full portfolio details."""
        snapshot = self._compute_snapshot()
        holdings_data = self.get_holdings()

        total_investment = Decimal('0')
        net_performance = Decimal('0')
        current_value = Decimal('0')
        total_fees = Decimal('0')

        for pos in snapshot.get('positions', []):
            inv = pos.get('investment', Decimal('0'))
            if isinstance(inv, (int, float)):
                inv = Decimal(str(inv))
            total_investment += inv
            vib = pos.get('valueInBaseCurrency', Decimal('0'))
            if isinstance(vib, (int, float)):
                vib = Decimal(str(vib))
            current_value += vib
            np_val = pos.get('netPerformance')
            if np_val is not None:
                if isinstance(np_val, (int, float)):
                    np_val = Decimal(str(np_val))
                net_performance += np_val
            fee = pos.get('feeInBaseCurrency', Decimal('0'))
            if isinstance(fee, (int, float)):
                fee = Decimal(str(fee))
            total_fees += fee

        activities = self.sorted_activities()
        created_at = min((a['date'] for a in activities), default=None)

        return {
            'accounts': {
                'default': {
                    'balance': 0.0,
                    'currency': base_currency,
                    'name': 'Default Account',
                    'valueInBaseCurrency': float(current_value),
                }
            },
            'createdAt': created_at,
            'holdings': holdings_data.get('holdings', {}),
            'platforms': {
                'default': {
                    'balance': 0.0,
                    'currency': base_currency,
                    'name': 'Default Platform',
                    'valueInBaseCurrency': float(current_value),
                }
            },
            'summary': {
                'totalInvestment': float(total_investment),
                'netPerformance': float(net_performance),
                'currentValueInBaseCurrency': float(current_value),
                'totalFees': float(total_fees),
            },
            'hasError': snapshot.get('hasErrors', False),
        }

    def get_dividends(self, group_by=None):
        """Return dividend timeline."""
        activities = self.sorted_activities()
        dividends = [a for a in activities if a.get('type') == 'DIVIDEND']

        if group_by:
            grouped = {}
            for div in dividends:
                d = div['date']
                amount = float(div.get('quantity', 0)) * float(div.get('unitPrice', 0))
                if group_by == 'month':
                    key = d[:7]
                else:
                    key = d[:4]
                grouped[key] = grouped.get(key, 0) + amount

            result = []
            for key in sorted(grouped.keys()):
                if group_by == 'month':
                    result.append({'date': f'{key}-01', 'investment': grouped[key]})
                else:
                    result.append({'date': f'{key}-01-01', 'investment': grouped[key]})
            return {'dividends': result}

        result = []
        for div in dividends:
            amount = float(div.get('quantity', 0)) * float(div.get('unitPrice', 0))
            result.append({
                'date': div['date'],
                'investment': amount,
            })
        return {'dividends': result}

    def evaluate_report(self):
        """Return portfolio report with xRay."""
        return {
            'xRay': {
                'categories': [
                    {'key': 'accounts', 'name': 'Accounts', 'rules': []},
                    {'key': 'currencies', 'name': 'Currencies', 'rules': []},
                    {'key': 'fees', 'name': 'Fees', 'rules': []},
                ],
                'statistics': {'rulesActiveCount': 0, 'rulesFulfilledCount': 0},
            }
        }
