"""Translated helper functions for portfolio calculations.

Generated by tt from TypeScript source files.
"""
from __future__ import annotations

import copy
import functools
import json
from datetime import datetime, timedelta, date
from decimal import Decimal


DATE_FORMAT = '%Y-%m-%d'


def get_factor(activity_type: str) -> int:
    """Return +1 for BUY, -1 for SELL, 0 for others."""
    if activity_type == 'BUY':
        return 1
    elif activity_type == 'SELL':
        return -1
    return 0


def get_sum(values):
    """Sum a list of Decimal values."""
    result = Decimal('0')
    for v in values:
        if v is not None:
            result += Decimal(str(v))
    return result


def parse_date(date_str):
    """Parse a date string to a date object."""
    if isinstance(date_str, (datetime, date)):
        return date_str if isinstance(date_str, date) else date_str.date()
    if isinstance(date_str, str):
        # Try common formats
        for fmt in ('%Y-%m-%d', '%d-%m-%Y', '%d/%m/%Y', '%Y%m%d'):
            try:
                return datetime.strptime(date_str, fmt).date()
            except ValueError:
                continue
        # Try ISO format
        try:
            return datetime.fromisoformat(date_str.replace('Z', '+00:00')).date()
        except (ValueError, AttributeError):
            pass
    return None


def reset_hours(d):
    """Return date with time set to midnight."""
    if isinstance(d, datetime):
        return d.replace(hour=0, minute=0, second=0, microsecond=0)
    return d


def get_interval_from_date_range(date_range, portfolio_start=None):
    """Convert date range string to start/end dates."""
    today = date.today()

    if date_range == '1d':
        start = today - timedelta(days=1)
    elif date_range == 'wtd':
        start = today - timedelta(days=today.weekday())
    elif date_range == 'mtd':
        start = today.replace(day=1)
    elif date_range == 'ytd':
        start = today.replace(month=1, day=1)
    elif date_range == '1y':
        start = today.replace(year=today.year - 1)
    elif date_range == '5y':
        start = today.replace(year=today.year - 5)
    elif date_range == 'max':
        start = portfolio_start if portfolio_start else date(2000, 1, 1)
        if isinstance(start, str):
            start = parse_date(start)
        if isinstance(start, datetime):
            start = start.date()
    else:
        # Try as year string: '2024' -> Jan 1 to Dec 31
        try:
            year = int(date_range)
            start = date(year, 1, 1)
            end = date(year, 12, 31)
            return {'start_date': start, 'end_date': min(end, today)}
        except (ValueError, TypeError):
            start = today - timedelta(days=365)

    return {'start_date': start, 'end_date': today}


def _date_format(d, fmt=None):
    """Format a date to string."""
    if d is None:
        return ''
    if isinstance(d, str):
        return d
    if isinstance(d, datetime):
        return d.strftime('%Y-%m-%d')
    if isinstance(d, date):
        return d.isoformat()
    return str(d)


def _is_before(a, b):
    """Check if date a is before date b."""
    a = _to_date(a)
    b = _to_date(b)
    if a and b:
        return a < b
    return False


def _is_after(a, b):
    """Check if date a is after date b."""
    a = _to_date(a)
    b = _to_date(b)
    if a and b:
        return a > b
    return False


def _difference_in_days(a, b):
    """Return difference in days between two dates."""
    a = _to_date(a)
    b = _to_date(b)
    if a and b:
        return (a - b).days
    return 0


def _add_milliseconds(d, ms):
    """Add milliseconds to a date."""
    d = _to_datetime(d)
    if d:
        return d + timedelta(milliseconds=ms)
    return d


def _sub_days(d, n):
    """Subtract n days from a date."""
    d = _to_date(d)
    if d:
        return d - timedelta(days=n)
    return d


def _each_day_of_interval(interval, step=None):
    """Generate each day in an interval."""
    start = _to_date(interval.get('start', interval.get('start', None)))
    end = _to_date(interval.get('end', interval.get('end', None)))
    if not start or not end:
        return []
    step_val = 1
    if isinstance(step, dict):
        step_val = step.get('step', 1)
    elif isinstance(step, int):
        step_val = step
    result = []
    current = start
    while current <= end:
        result.append(current)
        current += timedelta(days=step_val)
    return result


def _each_year_of_interval(interval):
    """Generate start of each year in an interval."""
    start = _to_date(interval.get('start', interval.get('start', None)))
    end = _to_date(interval.get('end', interval.get('end', None)))
    if not start or not end:
        return []
    result = []
    year = start.year
    while year <= end.year:
        result.append(date(year, 1, 1))
        year += 1
    return result


def _start_of_day(d):
    return _to_date(d)


def _end_of_day(d):
    return _to_date(d)


def _start_of_year(d):
    d = _to_date(d)
    return d.replace(month=1, day=1) if d else None


def _end_of_year(d):
    d = _to_date(d)
    return d.replace(month=12, day=31) if d else None


def _is_within_interval(d, interval):
    d = _to_date(d)
    start = _to_date(interval.get('start'))
    end = _to_date(interval.get('end'))
    if d and start and end:
        return start <= d <= end
    return False


def _date_min(dates):
    """Return minimum date from a list."""
    valid = [_to_date(d) for d in dates if d is not None]
    return min(valid) if valid else None


def _is_this_year(d):
    d = _to_date(d)
    return d.year == date.today().year if d else False


def _is_number(x):
    return isinstance(x, (int, float, Decimal))


def _sort_by(arr, key_fn):
    """Sort array by key function (lodash sortBy)."""
    if callable(key_fn):
        return sorted(arr, key=key_fn)
    if isinstance(key_fn, str):
        return sorted(arr, key=lambda x: getattr(x, key_fn, x.get(key_fn, '')) if isinstance(x, dict) else getattr(x, key_fn, ''))
    return sorted(arr)


def _uniq_by(arr, key):
    """Remove duplicates by key (lodash uniqBy)."""
    seen = set()
    result = []
    for item in arr:
        k = item.get(key, item) if isinstance(item, dict) else getattr(item, key, item)
        if k not in seen:
            seen.add(k)
            result.append(item)
    return result


def _lodash_get(obj, path, default=None):
    """Get nested value by path (lodash get)."""
    if isinstance(path, str):
        parts = path.split('.')
    else:
        parts = list(path)
    current = obj
    for part in parts:
        if isinstance(current, dict):
            current = current.get(part)
        elif hasattr(current, part):
            current = getattr(current, part)
        else:
            return default
        if current is None:
            return default
    return current


def _to_date(d):
    """Convert various date representations to date object."""
    if d is None:
        return None
    if isinstance(d, date) and not isinstance(d, datetime):
        return d
    if isinstance(d, datetime):
        return d.date()
    if isinstance(d, str):
        return parse_date(d)
    return None


def _to_datetime(d):
    """Convert to datetime."""
    if isinstance(d, datetime):
        return d
    if isinstance(d, date):
        return datetime(d.year, d.month, d.day)
    if isinstance(d, str):
        pd = parse_date(d)
        if pd:
            return datetime(pd.year, pd.month, pd.day)
    return None


def _parse_iso(s):
    """Parse ISO date string."""
    return parse_date(s)
